### ISSUE TITLE
Rigify generated rig does not move lower jaw teeth

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#10]
The rigify meta-rig moves the lower jaw teeth when being posed, but the generated rigify rig does not. 

There is probably some kind of logic to this that I just fail to see, but the teeth bones are treated different than the rest of the bones:

- they do not get renamed to DEF-...
- they have "deform" disabled

**Comment by gabrielmontagne** [comment]
The convention is that DEF- bones are bones with `deform` on.  

Bones that are not DEF- will have the deform off on purpose so they will not affect the vertex groups, will not be considered when doing automatic weight assignment, etc.   These are normally control bones or pivots or stuff like that.

In the "rigify way", if I'm not mistaken, you wouldn't assign weights to the top / bottom groups on the teeth mesh, but you would split the mesh into two different objects and directly parent each to each of the top / bottom bones.

On #9 I'd shared this demo from Todor Nikolov where he does just that.  Note that there's no weight assignment, https://www.youtube.com/watch?v=n8aCBKjPJRE&t=784s  

I'm doing this by hand on my MH characters and it works perfectly but you do need to separate the teeth into two separate objects.

**Comment by joepal1976** [comment]
Yes, I understood the parenting approach. I just wanted to test a quick (and probably dirty) way of supporting the current teeth assets. 

I think that in the end my current work-around should be an option which should default to off, so that people can make an informed choice about whether they want to break the rigify way of treating teeth. 

Maybe it'd be possible to automate the splitting of the teeth objects, for example based on their weight painting? It seems unlikely that the asset authors could be convinced to redo their assets to solve the rigify incompatibility, since the assets work perfectly fine with the other rigs.

**Comment by gabrielmontagne** [comment]
>  Maybe it'd be possible to automate the splitting of the teeth objects, for example based on their weight painting? It seems unlikely that the asset authors could be convinced to redo their assets to solve the rigify incompatibility, since the assets work perfectly fine with the other rigs.

I, myself, am using the vertex groups to split the mesh.  Edit mode vertex groups, select by the vertex group, separate by selection.  The resulting objects look fine to me.

**Comment by joepal1976** [comment]
Now the default is to try to automatically split teeth, but with options to either set up deforming or leave the teeth and rig as is.

**Comment by gabrielmontagne** [comment]
Very cool, thanks a lot!  I like the comments as well "this is the most MH way" ;-) 
I'll take it for a spin tonight.

**Comment by gabrielmontagne** [comment]
@joepal1976 , good stuff, man.  It worked perfectly well for me, both styles of rigging the teeth.  :muscle:

**Comment by gabrielmontagne** [comment]
A quick note, Todor published another video today addressing exactly these points for the jaw and the eyes.  For the MH style, weight painting eyes and teeth, he makes bones in the meta-rig with a particular Rigify type to automatically get them generated every time.  Looks a bit complicated, but perhaps more correct?  I wanted to share it here,  https://www.youtube.com/watch?v=Z1pL-ZUL0YU

**Comment by angavrilov** [comment]
With the switch to the new Rigify face in #41, I thinkthis should be fixed by default.

The workaround option still exists, but is off by default, and possibly broken.
