### ISSUE TITLE
Ability to hide slider images when modeling

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#103]
From #101 

While new users will benefit from a visual indication of what a modeling slider does, advanced users might feel that the images takes up too much space in the interface. 

There should be a toggle so that the images can be hidden if so desired.

At some point, this could be combined with some kind of mouseover solution for displaying the image dynamically, but this will take some research.

**Comment by joepal1976** [comment]
Added simple solution for toggling visibility of icons. Mouseover will have to happen at some other point in time.

**Comment by ashledombos** [comment]
working

**Comment by joepal1976** [comment]
Merged and working as expected.
