### ISSUE TITLE
Error: setup rigging is enabled, but could not find a rig to attach to

### ISSUE THREAD

**Issue by shrinktofit** [makehumancommunity/mpfb2#105]
Appear when loading cloths to a rigify rigged human. Steps to reproduce:

- Blender version: 3.1
- Add a human from scratch.
- Go to `Rig - Add rig`, change `Rig` option to `Game engine`, click `Add standard rig`.
- Select the generated rig then.
- Go to `Rig - Convert to rigify`, toggle on the `Keep meta rig`, click `Rigify`.
- Select the human mesh then.
- Apply any cloth asset on it.

![image](https://github.com/makehumancommunity/mpfb2/assets/28807867/a12c590b-369a-4e29-9fd8-c48bcf9cad69)

**Comment by joepal1976** [comment]
Thanks. I've pushed a fix which I think should solve the problem.

**Comment by joepal1976** [comment]
Assuming this works as expected.
