### ISSUE TITLE
Updating presets lists based on changes in the file system

### ISSUE THREAD

**Issue by Ashafix** [makehumancommunity/mpfb2#108]
**Is your feature request related to a problem? Please describe.**
If a new preset is manually created (e.g. by copying an existing preset) and or generating it via a script, the preset is not visible in the list 'From presets'.
If you try to load the new preset via the scripting console
`bpy.context.scene.MPFB_FPR_available_presets = 'human_template2'` it gives the following error
TypeError: bpy_struct: item.attr = val: enum "human_template2" not found in (...)`

**Describe the solution you'd like**
Ideally the list would automatically detect changes. If only the scripted version would work, that would also be fine.

**Describe alternatives you've considered**
Opening and closing blender is the only solution which works.

**Additional context**
I'd be happy to give it a try and submit a PR.

**Comment by joepal1976** [comment]
Sounds like a fair suggestion. 

I'll be a afk for a few days, so a PR would be welcome. 

What you'd need to do to add a "refresh" button in the new human from presets panel is in summary:

- Add a new operator for a button under src/mpfb/ui/newhuman/operators, for example by copying one of the existing ones and replacing the code in the execute method
- Import the new operator in src/mpfb/ui/newhuman/operators/__init__.py
- In the operator, make a call to src/mpfb/services/uiservice.py, the rebuild_importer_presets_panel_list() call
- Draw the button in the new human from presets panel, src/mpfb/ui/newhuman/frompresetspanel.py

**Comment by joepal1976** [comment]
Works for me. At some point, maybe the behavior should be configurable. But as you say, it is unlikely to be a problem in any realistic scenario. So send a PR and I'll merge it as it looks now.
