### ISSUE TITLE
Support mixamo

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#113]
Currently, it is rather cumbersome to use mixamo animations on MPFB characters. This is a combination of several issues, but a good start would be to have a 100% compatible rig for mixamo. With that in place, it'd be possible to do automatic mapping between a downloaded animation and a local character. It'd probably make uploading the character to mixamo a smoother ride too.

**Comment by joepal1976** [comment]
Moving weight painting to #116

**Comment by ashledombos** [comment]
I'm not used to Mixamo, but following your tutorial at https://youtu.be/Ct729M5dpfc,  it works perfectly (at least with the test I've just done)
Do you need more advanced or specific tests?

![image](https://github.com/makehumancommunity/mpfb2/assets/513335/e827f147-f6a4-4a2f-a6b3-457100ccee8f)

**Comment by joepal1976** [comment]
No, I haven't encountered any particular issues with it either, outside the weight painting stuff. 

Thanks for testing.
