### ISSUE TITLE
Suggestion of reordering of “Rigging” and “Apply assets” categories/sections

### ISSUE THREAD

**Issue by ashledombos** [makehumancommunity/mpfb2#115]
**Describe the solution you'd like**
From my understanding, the rigging process typically needs to be completed before applying assets, with some exceptions such as “Skins” and “Materials”. Given this, it seems to me that it would be more intuitive for users if the ”Rigging” category comes before the “Apply assets” one. Therefore, I suggest to move the "Rigging" category to the third position, just ahead of “Apply assets”, and below “Model”.

**Comment by joepal1976** [comment]
Sounds like a sensible suggestion.

Overall, the order of the panels is rather random atm. They just appear largely in the order I've added them.

**Comment by joepal1976** [comment]
I've pushed a fix for setting the _initial_ order of the panels. However, if you have a blend file that you saved when MPFB was already loaded, then that order takes presedence. There is no way for a python script to force the order of panels after the first time they were seen in a blend file (see https://blender.stackexchange.com/questions/24041/how-i-can-define-the-order-of-the-panels)

But for new users and for new blend files, the order should now be updated.

**Comment by ashledombos** [comment]
working
