### ISSUE TITLE
Adding best MH targets to assets packs

### ISSUE THREAD

**Issue by ashledombos** [makehumancommunity/mpfb2#117]
Currently, the selection of asset packs available for download on the mpfb2 website (http://static.makehumancommunity.org/assets/assetpacks.html) is impressive, but I think it could be further enriched by integrating a carefully curated selection of the best targets available for MakeHuman (http://www.makehumancommunity.org/targets.html).

There are certain targets developed by talented authors that allow for significantly more detailed or realistic refinements to various parts of the human body, including numerous facial details, muscle adjustments, hand features, tendons, ankles… I believe that including these in the MPFB2 asset packs list could dramatically enhance the the quality of the models created with mpfb2. Naturally, these could be categorized according to their licenses, and excluding any NSFW targets since those interested in such assets would likely know where to find them independently.

While I'm aware that it's relatively straightforward to import MakeHuman assets into mpfb2, I believe that not all mpfb2 users might think to do this, and more importantly, they may not have the motivation or the time to test all existing targets to select the best ones. Having a pre-selected set of high-quality targets readily available in the asset packs would save users significant time and effort, and help them to achieve more realistic results more efficiently.

If you find this idea interesting and if curating such a list would be too resource-intensive for you at this time, I’d volunteer my time to create a reasoned list, providing arguments for each selected target and why it would be a valuable addition to the asset packs.

**Comment by joepal1976** [comment]
It's a good idea to have such asset packs. I think most users will find the installation procedure for manually downloading a single custom target and manage to install it in MPFB prohibitively cumbersome. 

It would be very helpful if you could provide a categorized list of which targets you think should end up in such asset packs. The categorization need to be at least cc0/ccby, but more fine-grained topics are probably useful. Having NSFW as one topic is probably a good idea. Other topics might be "animal deforms" (such as cat face), "fantasy" (such as elf ears) and so on.

Providing an argument for each target seems a bit overkill though. As long as the targets work and provide some value, there's no reason to not put them in an asset pack.

If you want to take a swipe at this, I'd recommend not starting too big. Pick a few topics which you think provide the most value and find relevant targets for these.

For format, it would then be helpful if you could make a text file for each category/topic (such as "fantasy01_cc0.txt") and for each target make a semi-colon delimited line with title (as it appears at the top of the page in the asset library), author and url. For example:

    Elastic legs;culturalibre;http://www.makehumancommunity.org/target/elastic_legs.html

**Comment by ashledombos** [comment]
Hello,

I have been working on targets this week and it was more challenging than I initially thought.

To avoid any mistakes, I created a small script to download tables, fetch the names, authors, URLs, and the classifications given by the authors.

After that, I examined each target's documentation to determine the following:

    The license
    Compatibility with different versions (although I'm unsure of the impact this has in MPFB2)

I took note of four main aspects:

-     Whether an illustration was provided
-     The quality of the documentation (I focused on accuracy, even a simple but precise description is considered good. Conversely, some targets contain private references or irrelevant comments, such as the author's language skills)
-     Whether the name is self-explanatory. For example, "Foot Achilles Tendon" is clear, while "mYNEWtAIL0" is not. It wasn't always easy. For instance, is "Pikachu Head" self-explanatory to someone unfamiliar with Pikachu? Also, I realized after some time that the name displayed in MPFB (and MH) is the filename, not the target title itself, which sometimes may cause confusion (for example, the "Super Pointy Jaw" file name is "yaoi_chin2.target").
-     Ease of use - in other words, whether the target is straightforward to use (the user can immediately see the effect of the target), or if it requires working with other assets or under specific conditions.

I have downloaded and tested every target to verify their availability (I encountered 404 errors with 8 targets), check if they work, and note the following:

-     The region modified, following MPFB terminology (stomach, feet, chin, etc.)
-     The category, such as whether it's a detailed modification or primarily a significant transformation (I referred to this as a "morph" for my personal use)
-     The theme (realistic, fantasy, pose, etc.). Of course, it was not always easy to categorize.

I also added comments to some targets.

I'll now be working on suggesting some packs, but I have a few questions:

-     Would it be possible to add a "back" region (unless you consider "back" as part of the "torso" category), "eyeballs", "teeth" and "tongue" regions, and "multi-region" (or any other suitable name)?
-     Is there a way to display the actual target title instead of the filename in MPFB2?
-     I assume it's not easy to add a thumbnail from illustrations, provided they exist. My suggestion would be to instead have a link, which opens the target page when clicked. I don't know if this is feasible, though.

Here I attach my current work so you can see what I've done up to now.

[Tableau.csv](https://github.com/makehumancommunity/mpfb2/files/12138644/Tableau.csv)

**Comment by ashledombos** [comment]
I happened to notice today that the page located at http://static.makehumancommunity.org/assets/assetpacks/release_20221122.html mentions that all thumbnails are rendered inside Blender. This information partly addresses my third question. I'll proceed to work on creating thumbnails.

**Comment by ashledombos** [comment]
I've created an initial proposal for a targets pack. I would appreciate some guidance regarding my thumbnails. Are they correct, and what's the best way to annotate them? Should I just add yellow and orange arrows or should I also try to highlight shaping with dashed lines?
[realistic_details_arms_hand_cc0.zip](https://github.com/makehumancommunity/mpfb2/files/12161805/realistic_details_arms_hand_cc0.zip)

**Comment by joepal1976** [comment]
Well, you've sure been busy. :-) Sorry for being slow on reacting, I'm traveling a bit these days.

This is a very good start. I'll take a more detailed look at this, but to answer a few questions:

- Having additional categories (for example "back") is not a problem. On the contrary, it is probably a good idea to have more fine-grained categories than the ones that exist today. I'll still need to do something about #118 before being able to conveniently have additional categories though. But let's continue with the hypothesis that additional categories can be freely added
- It would be possible to have a meta-data file with the title and display that if available. This is not supported right now, but shouldn't be rocket science. 
- The compatibility setting can be ignored. It was relevant a decade ago when MakeHuman switched underlying base mesh, but since everything uses the same base mesh these days, the setting has lost its function
- 404s will be hard to do anything about. In all probability a file is missing server-side. This means that the only person having access to it will be the author
- Thumbnails should ideally be 256x256 png with a transparent background. Easiest is to check the "render properties" / "film" / "transparent" checkbox when rendering with cycles
- The thumbnail should have the same name as the target file but with ".png" extension instead of ".target"
- It is usually best to avoid having spaces in file names. In the asset library, it is assumed that "_" should be replaced with a space in the UI.

Regarding illustration of what it does, this is a bit more tricky. I'd say that if it is obvious what a target does (such as transforming the head to look like a cat), no extra illustrative lines need to be added. However, in cases where it is not obvious what the target does, maybe an arrow or a line needs to be added.

At the same time, doing this is a huge effort. And since thumbnails aren't even supported in the current "custom" tree, any thumbnail is an improvement. 

So I'd say that extra explanatory arrows or lines can be added only in those places where it is really necessary but skipped on the majority of the thumbnails.

As a late side-note: There is a live metadata file with all assets at http://www.makehumancommunity.org/sites/default/files/assets.json. For scripts etc, I usually read and parse this in order to extract relevant information. 

Anyway, I'll take a look at supporting asset packs with targets and use your sample asset pack as a test case.

**Comment by joepal1976** [comment]
In https://github.com/makehumancommunity/mpfb2/commit/504fc5aedd1ca262e822923d85fbac74f56638b8 I've added initial support for loading additional targets from the user data dir, along with thumbnails. 

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/34ec483a-39d5-4b0b-9cb7-b08337424a49)

The custom targets were loaded from this asset pack build:

[targets01_cc0.zip](https://github.com/makehumancommunity/mpfb2/files/12182815/targets01_cc0.zip)

Github won't let me attach json files, but the source pack information is this:

```
{
    "assets": {
        "elvs_ladies_elbow_dimples": {
            "final_name": "elvs_ladies_elbow_dimples",
            "node_id": "3049",
            "original_author": "",
            "original_url": "",
            "url": "http://www.makehumancommunity.org/node/3049"
        },
        "mindfront_arm_lower_shape": {
            "final_name": "mindfront_arm_lower_shape",
            "node_id": "1582",
            "original_author": "",
            "original_url": "",
            "url": "http://www.makehumancommunity.org/node/1582"
        },
        "mindfront_arm_upper_shape": {
            "final_name": "mindfront_arm_upper_shape",
            "node_id": "1583",
            "original_author": "",
            "original_url": "",
            "url": "http://www.makehumancommunity.org/node/1583"
        },
        "mindfront_arm_wrist_ulna": {
            "final_name": "mindfront_arm_wrist_ulna",
            "node_id": "1584",
            "original_author": "",
            "original_url": "",
            "url": "http://www.makehumancommunity.org/node/1584"
        },
        "mindfront_armpit": {
            "final_name": "mindfront_armpit",
            "node_id": "1585",
            "original_author": "",
            "original_url": "",
            "url": "http://www.makehumancommunity.org/node/1585"
        }
    },
    "description": "Realistic details for arms",
    "license": "CC0",
    "name": "targets01",
    "subdir": "arms"
}
```

All in all, I think it'd be best if I made a repo with the script files I have for working with asset packs, so we work with the same information and formats. My local dir is a bit messy though. I'll see what I can do about making it more palatable.

**Comment by ashledombos** [comment]
Thank you for your detailed answers and for the invitation to the private repository. I don’t find that your reaction was slow, on the contrary, in comparison to many open source projects I follow, I have a feeling of steady and regular development pace considering the size of the development team, and especially considering the summer period.

I've been using the Workbench render engine for the thumbnails as I found it gives a neutral look and the matcaps highlights the modifications well. However, I can switch to Cycles if needed. I'll resize the thumbnails to 256×256 and add a transparent background. When necessary, I'll also include arrows and dashed lines to better illustrate the changes.

Regarding the 404 errors, I've reached out to the authors via the dedicated pages for each asset.

Also, I wanted to ask if there's a preferred communication channel for these types of discussions (the forum for instance?) to avoid cluttering the GitHub issues.

**Comment by joepal1976** [comment]
The MPFB subforum on the forums might work, but maybe the discussions are of limited interest to anyone else.

If you have facebook/messenger, maybe you can send a message to makehuman on facebook.com/makehuman so we can exchange email adresses?

**Comment by joepal1976** [comment]
For people finding this issue: A first batch of target packs have been posted to http://static.makehumancommunity.org/assets/assetpacks.html

**Comment by ashledombos** [comment]
Maybe it would be better for your issue management to close this issue, as it’s ongoing ?

**Comment by Vidyut** [comment]
You guys are awesome-max.

Thank you, thank you, thank you.

**Comment by joepal1976** [comment]
@ashledombos : Yes, it's probably better to have more on-point issues in the asset staging repo if need be. 

@Vidyut : If you have suggestions for an asset pack with targets you find useful, just post a new issue here.
