### ISSUE TITLE
Support categorization of third part targets

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#118]
At the moment, all custom targets end up in a long list under "custom". In #117 there are plans for providing large sets of targets in asset packs. With this in place, the UX of the "custom" list will become unviable.

It would therefore be beneficial if third part targets could be placed in categories too. These categories could be the same as for the system targets, but they could also be things which did not exist before.

**Comment by ashledombos** [comment]
Do you need an additional column with category in the txt file (such as nose, hand, chin, ears etc.)?

**Comment by cgvirus** [comment]
Probably this is the accurate place.
I couldn't install target file or load them. Is it planned? Thanks,
https://github.com/makehumancommunity/mpfb2/issues/119

**Comment by joepal1976** [comment]
> Do you need an additional column with category in the txt file (such as nose, hand, chin, ears etc.)?

Yes, it might as well be included from start. No need to limit the category to existing ones though, if there is a need for other categories.

(although I assume this was for #117)

**Comment by joepal1976** [comment]
Note to self... Still missing is:

- Sorting
- Filtering

**Comment by joepal1976** [comment]
@ashledombos : Maybe I can prevaily upon you to give this a test spin with a few of the targets packs?

**Comment by ashledombos** [comment]
Sure, I’ll do!

**Comment by ashledombos** [comment]
Except for [228e91e](https://github.com/makehumancommunity/mpfb2/commit/228e91e98787f2f8ca3b0334f113b5a22611623f) about which Im not sure what to test, all is working (comments in respective patches)

**Comment by ashledombos** [comment]
I must say these improvement are huge time savers, thanks a lot.
