### ISSUE TITLE
Load Traget files

### ISSUE THREAD

**Issue by cgvirus** [makehumancommunity/mpfb2#119]
**Is your feature request related to a problem? Please describe.**
Ability to add custom morphs created with sculpt/transform tool. More like Daz3D custom morph.

**Reason**
- Gives artistic freedom to stylize character
- Easy to make cartoon character
 
**Describe the solution you'd like**
- Write the custom morph in the preset with morph name.
- Load the morph from json
or
- make a concept of custom morph character blend file, from which we can fetch the morphs.

**Describe alternatives you've considered**
See the video. Here I created details and shape tweaks and transferring it into another character.

https://github.com/makehumancommunity/mpfb2/assets/22106885/8baa713c-01ef-46d6-a7f6-05640d9a58cd

**Comment by cgvirus** [comment]
Seems Like we already have the system. Target. Do we have target loading system in mpfb2?

**Comment by cgvirus** [comment]
Found it. It was under model>custom, Which I had to make in data directory. This might needs to be more intuitive IMHO.

**Comment by joepal1976** [comment]
I do not disagree. The work with custom targets could definitely be improved. 

There's a "install custom target" button on the "library settings" panel, which I think should automate some of the steps.

**Comment by cgvirus** [comment]
Is it in the nightly build? I am only seeing "Load pack from zip"

**Comment by joepal1976** [comment]
That's strange. It should be a button right below the install asset pack button. 

How old is the nightly build? The install target button has been in there for at least a month.

**Comment by cgvirus** [comment]
Blender Version : 3.6.0
MPFB: 2.0.3 (latest)
OS: Linux Mint 21

![Screenshot from 2023-07-14 20-03-03](https://github.com/makehumancommunity/mpfb2/assets/22106885/abcc7579-aefc-456d-b7a4-17ba981e1d92)

**Comment by cgvirus** [comment]
There must be a bug. It is showing in Blender 3.3.8 but not 3.6.0.
MPFB: 2.0.3 (latest)
OS: Linux Mint 21
