### ISSUE TITLE
Parts of the UI missing in blender 3.6.0

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#120]
I'm getting reports that at least the "install custom target" button is missing in blender 3.6.0 whereas it shows up in blender 3.3.8. 

Will need to investigate and see what causes this and if there are other parts of the UI which does not show up.

**Comment by cgvirus** [comment]
After opening 3.3, now it has opened in 3.6.
That is strange. Probably a registry issue.

**Comment by joepal1976** [comment]
Ok, thanks. I'll keep this open for a while and see if the issue pops up again. 

If you happen to run into this or similar issues again, can you attach a log file?

**Comment by cgvirus** [comment]
sure

**Comment by joepal1976** [comment]
No more info for a month. Re-open if the issue is still there.
