### ISSUE TITLE
Missing eye texture brown.mhmat in system asset pack

### ISSUE THREAD

**Issue by cgvirus** [makehumancommunity/mpfb2#122]
Missing eye texture brown.mhmat in system asset pack. Without it, non procedural eye doesn't equip.

**Comment by joepal1976** [comment]
Thanks, can confirm this.

**Comment by joepal1976** [comment]
There is a new makehuman_system_assets available for download at http://static.makehumancommunity.org/assets/assetpacks/makehuman_system_assets.html

It now includes the missing eye textures.

**Comment by cgvirus** [comment]
Tested. Working. Thanks!
