### ISSUE TITLE
Make Skin needs more PBR texture placeholders

### ISSUE THREAD

**Issue by cgvirus** [makehumancommunity/mpfb2#124]
Make Skin needs these placeholders to create PBR textures:

- AO. First it needs to be multiplied with Albedo in a mix color node. Then the mix color node output goes to Base Color socket.
- Subsurface (for thickness/translucency map)
- Subsurface Color (For non red blood and mixed colored wax materials)
- Specular (Some asset and engine uses invert roughness which is specular in PBR)
- Emission (for colored lights)
- Emission Strength ( For emission masking) 

This will make it possible to author pbr textured materials properly.

**Comment by joepal1976** [comment]
Sounds reasonable. There are a bunch of side effects of adding more slots, but nothing dramatic. 

I'll take a look at this when I get back from vacations.

**Comment by joepal1976** [comment]
@cgvirus : If you happen to find the time, maybe you could take a look at the new model and see if it solves the problem?

I will not be surprised if it needs a bit of polishing here and there.

**Comment by cgvirus** [comment]
> @cgvirus : If you happen to find the time, maybe you could take a look at the new model and see if it solves the problem?
> 
> I will not be surprised if it needs a bit of polishing here and there.

Thanks for the work. I will let you know after tomorrow.

**Comment by joepal1976** [comment]
Thinking this works as expected.
