### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Miracle8248** [makehumancommunity/mpfb2#136]
Textures not coming whenever I export it in any version currently look at it it's the fbx export before and after
![Blender_8_26_2023_12_33_20_AM](https://github.com/makehumancommunity/mpfb2/assets/143383134/212872b8-f609-4251-be43-6a81a5b94af5)
![Blender_8_26_2023_12_36_06_AM](https://github.com/makehumancommunity/mpfb2/assets/143383134/3de0e262-8b06-4fb4-8552-6b24d7166875)

**Comment by joepal1976** [comment]
Can you clarify what exactly it is you are trying to do and what the problem is? Are you trying to export fbx from blender and then import it back again?

As a general note, how blender handles FBX import/export is outside what MPFB has any control over.

**Comment by Miracle8248** [comment]
Actually I want to export my model rigged and textured so that I can use that in any software but when i export from blender and upload it into blender I see there are no textures so how can I get textures in my fbx files even i export with textures
