### ISSUE TITLE
Import from MakeHuman application does not work

### ISSUE THREAD

**Issue by jtnicholl** [makehumancommunity/mpfb2#137]
**Describe the bug**
Importing a new human using the "from MakeHuman" option no longer works correctly, it only imports the armature and proxy mesh, then prints the error message below.

**Screenshots / logs**
```
An unhandled exception was encountered: Error: Object 'HumanName.body' already in collection 'Scene Collection'
. See console or log for information to provide in error report.
```

**Platform and versions**
I did a git bisect, this issue was introduced by d5fafd3, it worked fine before then.

**Comment by joepal1976** [comment]
Thanks. Yes, I see how that problem could arise. 

I'll take a look at it, but it will be a few days.

**Comment by joepal1976** [comment]
@jtnicholl I have pushed a fix now. Can you check if it solves your problem? It is in git now or in the nightly build tomorrow.

**Comment by jtnicholl** [comment]
Yes, seems to be working now, thanks.
