### ISSUE TITLE
head-scale-vert is incorrectly loaded as forehead-scale-vert

### ISSUE THREAD

**Issue by skunkbear** [makehumancommunity/mpfb2#139]
**Describe the bug**
When loading a preset, the value of head-scale-vert-decr-incr on the blender object is not set, and the value of head-scale-vert-incr/head-scale-vert-decr is instead applied to forehead-head-scale-vert-incr-decr. Effectively, this causes the preset to load with the vertical scale of just its forehead changed, instead of that of the whole head.

**Platform and versions**
 - OS: Windows 11
 - Blender 3.6.2
 - MPFB version 1/9 2023

**Comment by skunkbear** [comment]
_(Edited: At first I thought it saved incorrectly, but it actually seems to save correctly but load the .json incorrectly.)_

**Comment by joepal1976** [comment]
Ok, I think I see a scenario where this might happen. Would you mind sharing the json file here? It can be found by clicking  "system and resources" -> "directories" -> "user files" -> "config" and will be named "human.[name of the character].json".

**Comment by skunkbear** [comment]
[human.Loot.zip](https://github.com/makehumancommunity/mpfb2/files/12520787/human.Loot.zip)

**Comment by joepal1976** [comment]
@skunkbear I've pushed a fix which I think solves this problem. Can you check if your file is deserialized correctly now? The fix is in git now and will be in the nightly build tomorrow.

**Comment by skunkbear** [comment]
Yep, it seems to work correctly now. Thank you!

**Comment by joepal1976** [comment]
Assuming this works.
