### ISSUE TITLE
Rigify broken on new version of addon

### ISSUE THREAD

**Issue by gabrielmontagne** [makehumancommunity/mpfb2#14]
![image](https://user-images.githubusercontent.com/95913/126640033-89dfb632-c2db-40a6-ba34-7aa78e1e9307.png)

The rigify creation seems to be broken -- the teeth are not separated properly, but copied, and the eyes, eyelashes, etc. are not rigged or skinned.

Looking at the secondary meshes I see they don't have vertex groups.  Probably that's why the teeth split is not working correctly either.

**Comment by gabrielmontagne** [comment]
I'm not sure if the version is bumped every time, but this is where my git history says we are, 

![image](https://user-images.githubusercontent.com/95913/126640382-5bf0dd7c-4985-42f4-9bbb-5495beed03f1.png)
![image](https://user-images.githubusercontent.com/95913/126640414-40710cdd-cb86-4609-a236-95f4f3087e2f.png)

**Comment by joepal1976** [comment]
Thanks. I must've broken something when I was working with the rigify stuff.

**Comment by joepal1976** [comment]
Can you check if this commit solves the problem for you?

**Comment by gabrielmontagne** [comment]
Thanks! Yes, the new version fixes this problem!  Cheers :+1:
