### ISSUE TITLE
Error on the Presets

### ISSUE THREAD

**Issue by leroyteam** [makehumancommunity/mpfb2#142]
This is the first time I've written something here and it's about a problem that started happening to me when opening MPFB V2.0-a4 in Blender 3.3 and also in the latest version 3.6.2 LTS. It has always worked for me until today when I opened it and when I want to create a model it gives me an error that I must have the Presets selected. I click on the Preset option and I get the following error that I show in the screenshot, so I can´t create anything.

<img width="306" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/144623787/586a4574-9136-4f26-beb3-13ce7f6d725e">

<img width="265" alt="image" src="https://github.com/makehumancommunity/mpfb2/assets/144623787/3d3194db-c9c6-4a12-8db0-7198b2b32fe2">

OS Windows 10Pro 64
Blender 3.3 and 3.6
MPFB V2.0-a4 (Downloaded today 10/09/23)

**Comment by joepal1976** [comment]
That looks strange. Can you provide a log? See http://static.makehumancommunity.org/mpfb/faq/how_do_i_report_a_bug.html

And/or, is there an error message in the console? You should be able to show the console window by toggling it in the "window" menu (I think... at least in one of the main window menus).

**Comment by joepal1976** [comment]
Requested info not provided for a month. Re-open issue if the problem is still there.
