### ISSUE TITLE
Enabling the addon seems to do nothing

### ISSUE THREAD

**Issue by KR4325** [makehumancommunity/mpfb2#146]
**Describe the bug**
I installed the plugin on Blender and I did it the right way, but when I clicked on the check mark box, it didn't work at all.

**Screenshots / logs**
![Screenshot 2023-10-06 214232](https://github.com/makehumancommunity/mpfb2/assets/147221413/956e8def-bf24-412a-a780-bc30a7571e08)

**Platform and versions**
 - OS: Windows
 - Version of Blender: 3.6.4
 - Version of MPFB: 2.0.4 ( I downloaded MPFB 2 on 10/6/2023)

**Comment by joepal1976** [comment]
This might be a stupid question, but is the N-shelf visible here? MPFB registers panels on the N shelf. Press the "n" key to display it.

If the MPFB tab is not visible on the N-shelf after having enabled it, I'll need a screenshot of how the console window looks right after having checked the addon-checkbox as in your image. You can toggle the console window in the window menu.

**Comment by KR4325** [comment]
It works! Thank you so much! I pressed the N key on my keyboard and it worked.
