### ISSUE TITLE
eyelashes 01 does not show texture

### ISSUE THREAD

**Issue by vanda123025** [makehumancommunity/mpfb2#148]
Hello Sir/Madam 
eyelashes 01 does not show texture. It just happened to me on 2023-10-19, before that it worked fine.
![eyelashes 01](https://github.com/makehumancommunity/mpfb2/assets/148564950/feeaac31-8c80-48af-aa07-4709528636f8)

Other eyelashes can be used normally.
![Other eyelashes](https://github.com/makehumancommunity/mpfb2/assets/148564950/87629419-f980-4325-a8b5-8edcbf5b0066)

**Platform and versions**
 - OS: windows
 - Version of Blender 3.6.4
 - Version of MPFB 2.0.4

**Comment by joepal1976** [comment]
Did you change anything on that day, such as updating blender, updating mpfb or installing new asset packs?

In general, what is happening here is that the texture file for the eye texture is not found. Why that is so is harder to say. But if you have moved around files or directories for some reason that might be the cause.

**Comment by vanda123025** [comment]
Thank you for acknowledging my problem. I'm pretty sure I didn't change anything. But maybe someone else deleted some files. Because I share a computer with other people. The solution is just to reinstall, right?

**Comment by joepal1976** [comment]
Sorry, I missed your last comment. 

It might be enough to reinstall the relevant asset packs. The second action would be using the search for missing textures in blender's file menu I think, and point it towards the location where you have your blender user data.

**Comment by joepal1976** [comment]
Assuming this is not a bug per se
