### ISSUE TITLE
Button to display only active assets and targets

### ISSUE THREAD

**Issue by ashledombos** [makehumancommunity/mpfb2#154]
**Is your feature request related to a problem? Please describe.**
List of assets and targets can be very long, especially with community contributions, it could be interesting to quickly find currently active ones.

**Describe the solution you'd like**
I suggest the implementation of some dedicated button or toggle within the MPFB interface that, when activated, would filter and display only the active assets and targets. 

**Describe alternatives you've considered**
It could be a dedicated criteria users would have to manually input in the search bar. Though, a dedicated button would be more user-friendly.

**Comment by joepal1976** [comment]
I think the UI component most easily available would be checkboxed "show only equiped items" and "show only modified targets", defaulting to unchecked. 

It should not be hard to implement such filters, since the functionality for finding and highlighting the active items is already there.

**Comment by joepal1976** [comment]
@ashledombos : Maybe this matches the desired feature?

**Comment by joepal1976** [comment]
Closing as fixed
