### ISSUE TITLE
No Model menu in tab

### ISSUE THREAD

**Issue by fiferjanis** [makehumancommunity/mpfb2#155]
**Describe the bug**
I can create a doll from "scratch" but there is no "model" menu per tutorials and the like for editing after creation.

**Screenshots / logs**
<img width="450" alt="Screenshot 2023-11-08 at 02 37 10" src="https://github.com/makehumancommunity/mpfb2/assets/33758287/883e6803-4efe-45c5-a774-dba32deff05b">

**Platform and versions**
 - OS: Mac
 - Version of Blender: 3.6.2
 - Version of MPFB (approximate date when you downloaded it is enough): 7 Nov 2023

**Comment by fiferjanis** [comment]
It seems I somehow inadvertently baked it... maybe have some sort of warning if something will be destructive?

**Comment by joepal1976** [comment]
Actually, there is a warning:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/57c7a4b4-b85f-48c6-9148-1badd337b0b0)

But I agree it's easy to miss. In general, there are a lot of UX issues like that which should be addressed.
