### ISSUE TITLE
Skin from the MH System Assets loading throws a runtime error, 

### ISSUE THREAD

**Issue by gabrielmontagne** [makehumancommunity/mpfb2#16]
Hi, 

It seems the file `enhanced_settings.default.json` is not packed or generated on a clean install.  The whole `config` folder is missing on my  setup.

![image](https://user-images.githubusercontent.com/95913/141381334-4b8f5a3a-488d-4932-8ef5-0a6964e55042.png)

**Comment by joepal1976** [comment]
I think I've fixed this with https://github.com/makehumancommunity/mpfb2/commit/14c24bcb540df39e56b2e23e65cc7bfac4237978

Can you test again?

**Comment by gabrielmontagne** [comment]
I'm trying the latest build, the error changed, became a bit more dramatic, if I may say so, 
![image](https://user-images.githubusercontent.com/95913/141682577-ab9adca9-5a41-4605-83e1-d33a6575b7f0.png)

**Comment by gabrielmontagne** [comment]
Apologies, I might have done something wrong. 
Tried again, from scratch, all is working fine.  
Thanks a lot for the fix!

**Comment by joepal1976** [comment]
Ok, I'm going to think this is fixed then. Just re-open if the problem pops up again.
