### ISSUE TITLE
Can't create human on Blender 4.0.1 due to disabled 'Wavefront OBJ Format' addon

### ISSUE THREAD

**Issue by JS-E** [makehumancommunity/mpfb2#160]
**Describe the bug**
I can't create a human in the plugin due to an error of Import-Export Wavefront OBJ format addon being disabled, but i believe this addon doesn't exist for Blender 4.0.1

**Screenshots / logs**

![image](https://github.com/makehumancommunity/mpfb2/assets/33073990/34b72b41-8005-438e-b0fb-c62ea4aa1343)

[INFO ] uiactions ..............................: Executing MPFB_OT_HumanFromPresetsOperator
Error: The "Import-Export Wavefront OBJ format" addon seems to be disabled. You need to enable this in the preferences.

**Platform and versions**
 - OS: Windows 11
 - Blender 4.0.1
 - Downloaded latest version today

**Comment by joepal1976** [comment]
Just checking: Are you using the blender4 specific build here? That is, did you download a file called mpfb2-blender4-*.zip?

**Comment by JS-E** [comment]
@joepal1976 I downloaded this one -> http://files.makehumancommunity.org/plugins/mpfb2-blender4-latest.zip

**Comment by joepal1976** [comment]
Can you post a screenshot of the system console right after having tried to install from zip? Assuming you are on windows, it should be possible to toggle it in the "window" menu.

**Comment by Sphynxcolt** [comment]
> Can you post a screenshot of the system console right after having tried to install from zip? Assuming you are on windows, it should be possible to toggle it in the "window" menu.

Is this to me?
The log is right there, underneath the Preferences window.

Which "window" menu do you mean?

**Comment by joepal1976** [comment]
Yes, it was to you. 

The problem here is that I see no error message. My hope was that if I could see the entire console window there would be a clue as to what's wrong. Atm I have absolutely nothing to go on, as it works on my side and there is no indication on what causes the problem.

The "window" is the main menu "window" in the top of the blender window. It is between the "render" and "help" menus.

As a observation, there seems to be something problematic with the paths in your blender installation, or something has happened with the installation directory. You've got 10+ warnings about missing module files for other addons, unrelated to MPFB.

**Comment by Sphynxcolt** [comment]
I installed the addon again, again, it doesnt appear in the list. 
![image](https://github.com/makehumancommunity/mpfb2/assets/56783893/49014e60-c978-4413-9484-4924e137dccb)
Everything after the installed module of mpfb zip was just me removing the ghost scripts/"missing scripts" (I might have removed them at some point incorrectly) and can be ignored.

**Comment by joepal1976** [comment]
Well, I'm stuck. I've been trying to replicate the phenomena (both the error message and the addon not showing up) locally, on both windows and linux, but I can't trigger it. So right now it seems unlikely I'll be able to find anything that solves the problem.

If you reinstall blender, I'd suggest also clearing out the user data. Once the current version of blender is uninstalled, you might want to open "c:\Users\sphyn\AppData\Roaming\Blender Foundation" and move all subdirectories to somewhere else. This way you'll get a clean slate when installing the new blender.

**Comment by Sphynxcolt** [comment]
So I tried with a fresh install, and it still doesnt shop up in the addon list.

**Comment by joepal1976** [comment]
I'm reaching for straws here, as I have no natural explanation for why you don't either see the addon or at least get an error message. I can only speculate, although what I come up with sounds improbable even to me. 

Anyway, what I'd like to know is if the files even end up in the right location when you select the addon zip in blender. 

Can you post screenshots of the following dirs (if they exist) :

- c:\Users\sphyn\AppData\Roaming\Blender Foundation\4.0
- c:\Users\sphyn\AppData\Roaming\Blender Foundation\4.0\scripts\addons
- c:\Users\sphyn\AppData\Roaming\Blender Foundation\4.0\scripts\addons\mpfb

If these dirs are missing, I'd take a look at windows defender or any other kind of antivirus solution to see if they were blocked or removed or something.

For reference, this is how they look on my windows 11 machine when I have installed from zip in blender:

<img width="1402" alt="dirs1" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/d90ab95b-62a4-49c5-9114-81fbe61b8182">
<img width="1402" alt="dirs2" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/83749354-b441-417f-a0cc-d6a1d649730b">
<img width="1402" alt="dirs3" src="https://github.com/makehumancommunity/mpfb2/assets/10105480/e58b11e2-da68-454f-ae03-0894821dc907">

**Comment by adrianwez** [comment]
I was facing the same error until I read this part:

> The reason I ask is because in the screenshot you provide, the version on the tab is listed as "...-a3". The blender4 versions are listed as "...-a4" ...

The latest link is referencing to a version that provida a "...-a3", so I tried the one above and re-started Blender. Everything works fine now and it is now listed as "...-a4".

This one:
![MPFB_RightOne](https://github.com/makehumancommunity/mpfb2/assets/113318115/4731a73d-8911-45c7-ba58-66335aaefb95)
