### ISSUE TITLE
MPFB2 alpha 3 does not work with blender 4

### ISSUE THREAD

**Issue by Mohammad9760** [makehumancommunity/mpfb2#163]
**Describe the bug**
I understand that MPFB uses the OBJ importer addon, but Blender ver 4.0+ now supports OBJ import/export natively and don't use the add-on anymore.

**Screenshots / logs**
The "Import-Export Wavefront OBJ format" addon seems to be disabled. You need to enable this in the preferences.

**Platform and versions**
 - OS: Linux Ubuntu 21
 - Version of Blender 4.0
 - Version of MPFB 2.0.3

**Comment by joepal1976** [comment]
Did you use the blender 4 specific build? Alpha 3 and the normal build are not compatible with blender 4.

**Comment by Mohammad9760** [comment]
> Did you use the blender 4 specific build? Alpha 3 and the normal build are not compatible with blender 4.

what's the specific build? I got the new Blender 4.0 from blender.org.

**Comment by joepal1976** [comment]
By the way, if you download the other zip addon now, you might want to also take a look at http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html

**Comment by amoshydra** [comment]
The Blender 4 specific build is only available as a Nightly build for now.

We need to get it from the plugin folderhttp://files.makehumancommunity.org/plugins/

**Comment by joepal1976** [comment]
I'm going to assume that this was the problem.

**Comment by Mohammad9760** [comment]
> The Blender 4 specific build is only available as a Nightly build for now.
> 
> We need to get it from the plugins folder http://files.makehumancommunity.org/plugins/

I will check it out, thanks!

**Comment by SpaceView** [comment]
Dear, I got the same problem, with Blender 4.1 on windows 10.  any idea?
