### ISSUE TITLE
Hardcoded local paths forgotten in blender4 nightly

### ISSUE THREAD

**Issue by euhmeuh** [makehumancommunity/mpfb2#164]
Fresh install of Blender 4 and the nightly build of mpfb2, blender4 branch

https://github.com/makehumancommunity/mpfb2/blob/f683f8ee904c3cb2b411d67995869630cd24116c/src/mpfb/entities/nodemodel/v2/composites/nodewrappermpfbsystemvaluetextureeyelids.py#L131

https://github.com/makehumancommunity/mpfb2/blob/f683f8ee904c3cb2b411d67995869630cd24116c/src/mpfb/entities/nodemodel/v2/composites/nodewrappermpfbsystemvaluetextureeyelids.py#L166

Hello!
I think you forgot those hardcoded paths in your code. It's breaking the plugin when trying to apply any procedural skin to a model.

Cheers and thanks for your work on Blender 4 compatibility! I can't wait for those changes to be merged!

**Comment by joepal1976** [comment]
This can't possibly have ever worked for anyone...

Anyway, I've pushed a fix now. It will be in tomorrow's nightly build or can be fetched from git.

**Comment by euhmeuh** [comment]
Yeah thanks for the quick reply! I'll test that tomorrow. Have a nice day! :grin:
