### ISSUE TITLE
Provide OpenPose json export

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#165]
It should be possible to export a pose to OpenPose json format, in order to use in, for example, ControlNet for SD generative AI.

**Comment by joepal1976** [comment]
There's an openpose export panel under the "operations" panel now. It works well enough to play around with.

**Comment by joepal1976** [comment]
Example of usage, multiple persons:

![multi_blender](https://github.com/makehumancommunity/mpfb2/assets/10105480/67c9dcf8-2fc4-4d47-8652-a6a4f9dec15e)
![multi_json](https://github.com/makehumancommunity/mpfb2/assets/10105480/5470ff6b-2c3b-4e72-b9f2-2c1bfe73141e)
![multi_output](https://github.com/makehumancommunity/mpfb2/assets/10105480/f970724e-6a67-4142-b23e-f288ee69655e)

**Comment by aheger76** [comment]
Hi! Is this feature available in latest mpfb2-blender4 nightbuild? Because I couldn't find it on the mpfb2 UI. Or will it be available soon?
Thanks in advance.

**Comment by joepal1976** [comment]
Yes, it should be there. With a rig selected, it should appear under "Operations" -> "OpenPose". 

If it is not visible there, can you post a screenshot of the operations panel as it looks when expanded?

Also, take a look at this to make sure you're not affected by a cache problem: http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html
