### ISSUE TITLE
MPFB should check if a name is already taken before using it in rigify generate

### ISSUE THREAD

**Issue by gabrielmontagne** [makehumancommunity/mpfb2#17]
It's not always, though.  Normally not when I just go directly through the steps, but after a while of tweaking and adding assets.
I'm trying to come with a reliable way to reproduce. 

![image](https://user-images.githubusercontent.com/95913/141700143-cb0b6060-0220-4a8c-9c92-6fe66fd16ce3.png)

**Comment by gabrielmontagne** [comment]
Looking around, it seems to be in rigify, not in mpbf2.  Hm.

**Comment by gabrielmontagne** [comment]
I know what it is.  On the "generate rigify rig" dialogue I'm setting a name that's already used by an existing object (in my case, a mesh).  All crashes from there onwards, rigify thinking it's operating on an armature, but it's actually a mesh (it's actually a *mess* : P )  .   

I wonder if mpfb2 should or shouldn't check?  It ends up being a runtime error so maybe it should, even if it's my fault somehow?   Or maybe, when it generates the armature it should check the resulting name, in case it has a .001 or something? 

Thinking out loud.  I'd be fine if this is closed with a "problem between keyboard an chair" resolution.  But still it'd be nice to get a warning instead of a crash.

**Comment by joepal1976** [comment]
If it is as simple as checking if the name is already used by a different object, we might as well perform the check. It shouldn't take more than a few milliseconds.

**Comment by joepal1976** [comment]
I think this works as intended.
