### ISSUE TITLE
The helper geometry is visible in exports from blender

### ISSUE THREAD

**Issue by Drinkingpants74** [makehumancommunity/mpfb2#174]
**Describe the bug**
When I export the created character from Blender to Godot, it's nothing like what I'm seeing in the Blender view. The weird part isn't just that it's exporting wrong, it exporting with things I don't have installed (like the male genitals sticking out of the bottom of the robe).

When I deselect "Mask Helpers" from the Create Menu, then I actually see the character that's being exported.

**Screenshots / logs**

Inside Blender:
![Screenshot 2024-01-22 at 4 31 38 PM](https://github.com/makehumancommunity/mpfb2/assets/60319968/f4a5c1b3-b354-4e86-8711-0f0164ae0144)

Inside Godot:
![Screenshot 2024-01-22 at 4 32 54 PM](https://github.com/makehumancommunity/mpfb2/assets/60319968/f5997d06-76ce-46d4-9300-e368417fd83a)

Mask Helpers Off:
![Screenshot 2024-01-22 at 4 34 14 PM](https://github.com/makehumancommunity/mpfb2/assets/60319968/0320cc6e-f865-4e86-874c-f21c030d09cc)

**Platform and versions**
 - OS: macOS
 - Blender: 4.0.2
 - MPFB2: 20240122 [Downloaded From the Official Sources Here](http://files.makehumancommunity.org/plugins/)

**Comment by joepal1976** [comment]
The helper geometry is an integral part of MPFB. It is there for fitting clothes. Without it, it would not be possible to equip most mesh assets. However, it does not make much sense to keep it outside Blender unless you are building an application where you need to equip additional assets.

So if you don't need the helpers, you should remove them before exporting. There is a button for this under operations:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/95ecd4ca-7b0a-4813-ab0f-8158c6f00ae7)

You might want to consider also baking the shape keys for much the same reasons.

Another approach would be using a low poly proxy mesh and simply deleting the "body" mesh before exporting. In many game situations, using the full base mesh is probably overkill.

As a side note, there is a project for using MPFB directly inside godot, see https://github.com/NitroxNova/Humanizer ... Possibly there is something there which might be of use to you.

**Comment by Drinkingpants74** [comment]
That was the problem. Thanks for the help 😁. I'll also give that project a peek.
