### ISSUE TITLE
Attribute Error in Skin Shader

### ISSUE THREAD

**Issue by Debiprasad16** [makehumancommunity/mpfb2#176]
Every time I'm using the default skins for my human character or eyes library, it's always showing the error: ""AttributeError: 'ShaderNodeTree' object has no attribute 'inputs' "".

- I'm using blender 4, and yes, I used the blender 4 specific build.

- I downloaded mpfb 2.0.4 today, and here is the link which I've downloaded for Blender 4.0.

http://files.makehumancommunity.org/plugins/mpfb2-blender4-latest.zip

**Screenshots / logs**
- Below I've attached the screenshot of the log showing the detailed error of skin library. The same type of error also occurs for eyes library. 

![blender mpfb error](https://github.com/makehumancommunity/mpfb2/assets/68688148/7faf1bf1-3474-4a6c-ba14-6df0be437378)

 - OS: Windows 11
 - Version of Blender: 4.0
 - Version of MPFB: 2.0.4

**Comment by joepal1976** [comment]
This looks strange. According to the stack trace, the line causing the crash is the "else" statement, which by all reason is not the case. 

Can you provide screenshots of the resources panel and the library settings panel? (see bottom of post for where they are)

Also, it'd be helpful if you took a look at http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html to see if it might be relevant to your situation.

Finally, I've forced a rebuild of all plugins in case something is outdated. Can you download again and see if changes anything?

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/fe03634d-5444-4e57-ab21-ae951d3f157d)

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/ad9a2b8f-b4ef-4806-b84e-de63d65b865e)

**Comment by Debiprasad16** [comment]
Okay, Thank you so much. Everything is now fixed and working properly. I've re-downloaded the pack as you said, and it fixed the errors. 

Again, Thanks 👍🏻
