### ISSUE TITLE
help with correcting rigify fingers orientation upon generation via mpfb2

### ISSUE THREAD

**Issue by dhyowi** [makehumancommunity/mpfb2#178]
Hi. I'm just wondering why rigify fingers are not bending the right way anymore after generation using mpfb2. Can you help me figure this out? 
Thanks a lot.

**Comment by joepal1976** [comment]
To clarify, what exactly is the problem? This is how it looks for me on a blender4 version of MPFB2:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/7a1114bb-52ea-4e48-89c7-789838f4196c)

Maybe you can provide a screenshot illustrating the problem?

**Comment by joepal1976** [comment]
No information for a month. Reopen if still an issue.

**Comment by dhyowi** [comment]
![Screenshot 2024-06-07 165220](https://github.com/makehumancommunity/mpfb2/assets/21953048/73918113-91d0-49a4-8935-1676869e555d)

Sorry for the very late reply and thank you for your interest. My computer broke down.

**Comment by joepal1976** [comment]
Stupid question, but are you rotating around the correct axis? Ie, select bone, keys r-x-x, then rotate?

**Comment by dhyowi** [comment]
It's just the S button to bend the fingers, right?

**Comment by joepal1976** [comment]
@dhyowi : This too works for me. I select the master bone for the index finger:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/41c30ff2-5d86-408b-9364-415780db9fb4)

Then I click "s" and scale down a bit:

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/8507e68d-cb4b-4ad3-afb8-d1d08e222769)

Can you provide information about the following?

- Is this a completely new character or a character you created previously? (as in with an earlier version of mpfb, blender or rigify)
- With finger detail layer enabled, in rig edit mode and with the first bone selected on the index finger (ie f_index.01.L)... what roll does it have?
- Exactly which version of blender is this?
- Exactly which version of mpfb is this?

For the last two, a screenshot of the "system and resources" panel expanded would do fine.

**Comment by joepal1976** [comment]
You are using a very, very old version of MPFB. Rigify has received several updates since november (it says your build date is november 25:th, 2023). 

Maybe you can start with trying a nightly build of more recent date? The download links are here: https://static.makehumancommunity.org/mpfb/downloads.html

If you actually did upgrade recently but still see that build date, you might need to take a look at https://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html

**Comment by dhyowi** [comment]
I have updated to the version that you sent a link over. Is there a way to correct the orientation of the existing rigify rig? Thanks for taking the time man. Appreciate it a lot.

**Comment by joepal1976** [comment]
If you haven't modified the mesh, my primary suggestion would be to save the character as a preset ("manage presets" -> "human presets") and then load a fresh copy of the character. 

A more cumbersome alternative would be to load a completely new character with a rigify rig and check the roll values of the corresponding bones in the hand and update these roll values on your existing character. I'm not sure this would work, but it might be worth trying.

**Comment by dhyowi** [comment]
Thanks! I'm getting this error message when I try to save.
![Screenshot 2024-06-11 044605](https://github.com/makehumancommunity/mpfb2/assets/21953048/49e92f2d-2cc6-4129-876d-e3d723272b20)

**Comment by joepal1976** [comment]
Yeah, my bad. Sorry, forgot about that. You don't happen to have kept the rigify meta rig around when generating the final rigify rig?

I'll take a look at the serialization logic tomorrow anyway, and see if the limitation about generated rigify rigs can be worked around.

**Comment by dhyowi** [comment]
As a matter of fact I have. It's still there.

I'm showing you a screenshot of an earlier saved file of the same project wherein no change of posture has been done yet. The rigify rig is in the correct orientation but the mesh is deformed when I use S to bend the fingers.

![Screenshot 2024-06-12 074405](https://github.com/makehumancommunity/mpfb2/assets/21953048/a94a212b-36ac-4ceb-978e-88ca9fccb5a0)

**Comment by joepal1976** [comment]
And this is from a preset that was opened with a new version of MPFB today? Or is it a character that was saved in a blend file with an earlier version of MPFB?

If it was from a preset, can you paste the contents of the preset file here? You can find it by going to "system and resources" -> "directories" -> "user files" -> "config". There should be a json file there with the name of the character, prefixed with "human."

**Comment by dhyowi** [comment]
It's from scratch that I customized with an earlier version of MPFB2 that I opened with the new version. But the thing is, it was like this with the old version as well. It's the same model as from the earlier one I was talking about. I was trying to look for a saved file that has a good working finger animation. This is the earliest saved file. I have like twelve saved versions from making the hair and clothes. But just trying to salvage the work done on the model like facial features and such. The first one I sent you was the twelfth version and this is the first. The fingers are the only ones that are having deformations like this. All the rest seem to be working flawlessly.

**Comment by joepal1976** [comment]
There are two parts of the discussion here: 

- Trying to figure out how to salvage your model and solve the problem you have
- Figuring out if this still happens when opening characters from presets or creating completely new characters

For the first part, I've now pushed a change which should allow you to serialize the character to a new character preset. With some luck, the orientation should be correct when you create a new character "from preset" using that preset. The change is in git now, and will be available from the nightly build tomorrow.

For the second part, I've been unable to create a character which has the same problem. This makes it hard to figure out what would need to be done and if there's a remaining problem. If your character still has a problem when reloading it from the preset, I'll need to see the contents of the preset file to get any further.

**Comment by dhyowi** [comment]
Thank you very much for taking the time to listen to my woes and finding a way to resolve them. Can't thank you enough. Well, new characters don't seem to carry on the problems I was having previously. Just installed the new night builds and I am now able to save the preset and load it to the new file. I guess my issue is now resolved. Thank you very much once again, man. Really appreciate it a lot. Let me know if there's anything I can do for you.
