### ISSUE TITLE
MakeSkin misbehaves on blender 4

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#188]
It seems some glitches have been introduced in MakeSkin in the transition to blender 4. It needs to be thoroughly tested and fixed.

At least the following need to be investigated:

* Not all texture nodes are created on material creation. At least emission color is missing, potentially others
* On a mesh extracted by makeclothes but with the material removed, makeskin does not show the create material panel
* Saving alternate material for low poly eyes does not seem to work (at least it doesn't show up in list)

**Comment by Vidyut** [comment]
I don't know if this is related, but the multilayered skin doesn't load for me anymore in Blender 4. It used to work on a much less powerful laptop before - so I know what you say that it needs to be baked before use, but I can't load it to customise it before baking. I think this could be related to this issue - both handle the complexity of generating skin, right?

**Comment by joepal1976** [comment]
@Vidyut That's a different issue. The multilayered skin model is heavy and should be looked at, but this issue is about the makeskin model which is non-procedural.

**Comment by joepal1976** [comment]
Can't replicate the two last items. Going to assume I did something wrong when they happened the first time.

**Comment by joepal1976** [comment]
Works as intended, open new issues if something is strange.
