### ISSUE TITLE
Blender 3.0.0 python call for removing materials does not work - old materials remain when selecting new skin

### ISSUE THREAD

**Issue by Iansamit** [makehumancommunity/mpfb2#19]
In the version downloaded on 29 Dec 2021, some (maybe all but I haven't yet checked) skins incorrectly label the materials.

The most problematic is that the main "body" material is labeled "Human.toenails". In the case of the default skin, there is no material labeled "Human.body"; in the case of there is a "Human.body" material slot but no vertices have been assigned to it. 

There are also duplicate material slots of most materials, although only one of each has vertices assigned to it.

**Comment by joepal1976** [comment]
I will need some more information to go on here. Where/how was the skin assigned? On import or when applying it on a character?

If I create a character from scratch, click a skin, enter edit mode and click select for the toenails material, it looks correct for me:

![toenails](https://user-images.githubusercontent.com/10105480/147682478-e76e19b0-8779-479c-a33c-d9b4df74ca80.png)

Can you provide a screenshot of how it looks on your side?

**Comment by joepal1976** [comment]
Also, are you using any body proxy?

**Comment by Iansamit** [comment]
Hi Joel,
Sorry I should have done more research myself before posting. The problem seems to be specific to mhm import.

To make sure this was not caused by my models, I saved the default MH model to a file, and imported it via New human > From presets. At this point, the various skin materials worked as expected:
![skin_bug_01](https://user-images.githubusercontent.com/5831121/147869515-5c4f57cb-756b-423b-b442-d0be6a1a04bc.png)

After loading the default skin via Apply assets > Skin Library, the list of materials for the model changed. At first, it seemed that Human.body has been replaced by Human.body.001, while there were duplicates for toenails, ears and genitals. However, there were no vertices assigned to Human.body.001.
![skin_bug_03](https://user-images.githubusercontent.com/5831121/147869624-dda0fda4-513c-4776-b238-f1019f2dd7f6.png)

The body vertices had been assigned to Human.toenails.001. 
![skin_bug_02](https://user-images.githubusercontent.com/5831121/147869658-874bb897-9029-4382-8ffc-7074f5d48758.png)

Please let me know if I can help further.

**Comment by joepal1976** [comment]
Thank you for this detailed report. This should give me plenty to go on. 

I think I see what the problem might be, so it should not be that hard to fix. But it might take a few days.

**Comment by joepal1976** [comment]
Something is wrong with the remove material call in blender 3.0.0. The code snippet is very short and easy:

```code=python
    @staticmethod
    def delete_all_materials(blender_object):
        for x in blender_object.material_slots:
            blender_object.active_material_index = 0
            bpy.ops.object.material_slot_remove({'object': blender_object})
```

This works perfectly fine in blender 2.92, but does nothing in 3.0.0. Not even an error message is given.

I'm stumped. As of now, I don't know any working way of removing a material using a python script. 

But research is ongoing.

**Comment by joepal1976** [comment]
Ok, I think I've managed to fix this now. Can you check if it solves your problem?

**Comment by Iansamit** [comment]
Sorry for the slow response. Yes, I just downloaded the latest version and the problem is gone.
