### ISSUE TITLE
No Colours in blender 4.1

### ISSUE THREAD

**Issue by Iamwhaphark** [makehumancommunity/mpfb2#195]
There is no color in any of my assets. When I choose a skin color it just slightly changes color to a slight gray color.  It didnt match my skin. Then, I tried to change skin it still didn't change anything. I gave up and went to the clothing part. I tried to apply one of the clothing but it didn't have any colour.

**Comment by joepal1976** [comment]
Dumb question, but are you in "solid" mode in blender? Does it still have no color if you render?

I'm not sure I understand what happens here. I'd need to see some screenshots in order to give some kind of answer.

**Comment by Iamwhaphark** [comment]
It worked thank you very much! I am sorry for asking such a stupid question since I am quite new to blender.
