### ISSUE TITLE
Some models do not import correctly when importing via "Import MHM"

### ISSUE THREAD

**Issue by Iansamit** [makehumancommunity/mpfb2#20]
I have several models created with MH that I am importing into Blender (example here as a txt file [Mick2.txt](https://github.com/makehumancommunity/mpfb2/files/7874215/Mick2.txt)).
 
If I open the model in MH and import it via "Import human", the model imports without error:

![Object Via MH](https://user-images.githubusercontent.com/5831121/149608181-0c9908fd-959a-4309-addf-4b28dbd096fc.png)

Changing to Edit Mode in Blender also shows that the model has imported correctly.
![Edit Via MH](https://user-images.githubusercontent.com/5831121/149608227-8fe70701-725b-45c8-b7aa-432c2541c3d2.png)

However, if I import the same model via "Import MHM", I get the following error:
```

Python: [ERROR] mpfb.init ..............................: Unhandled crash 
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/ui/newhuman/operators/humanfrommhm.py", line 43, in execute
    basemesh = HumanService.deserialize_from_mhm(self.filepath,
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 870, in deserialize_from_mhm
    basemesh = HumanService.deserialize_from_dict(human_info, mask_helpers, detailed_helpers, extra_vertex_groups, feet_on_ground, scale, subdiv_levels, load_clothes=load_clothes)
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 652, in deserialize_from_dict
    HumanService._load_targets(human_info, basemesh)
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 624, in _load_targets
    TargetService.load_target(basemesh, target_full_path, target["value"], target["target"])
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/targetservice.py", line 442, in load_target
    raise ValueError("Must specify a valid path")

Must specify a valid path

Traceback (most recent call last):
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/ui/newhuman/operators/humanfrommhm.py", line 43, in execute
    basemesh = HumanService.deserialize_from_mhm(self.filepath,
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 870, in deserialize_from_mhm
    basemesh = HumanService.deserialize_from_dict(human_info, mask_helpers, detailed_helpers, extra_vertex_groups, feet_on_ground, scale, subdiv_levels, load_clothes=load_clothes)
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 652, in deserialize_from_dict
    HumanService._load_targets(human_info, basemesh)
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/humanservice.py", line 624, in _load_targets
    TargetService.load_target(basemesh, target_full_path, target["value"], target["target"])
  File "/home/ian/.config/blender/3.0/scripts/addons/mpfb/services/targetservice.py", line 442, in load_target
    raise ValueError("Must specify a valid path")
ValueError: Must specify a valid path

location: <unknown location>:-1
```

![Object Via MHM](https://user-images.githubusercontent.com/5831121/149608264-fd3ab14d-4870-489d-946b-d10e8db3082e.png)

Also, changing to edit mode, the model changes to (I think) the default model:

![Edit Via MHM](https://user-images.githubusercontent.com/5831121/149608276-4db0f82b-8fe3-4a1e-975c-acdd342f53b6.png)

**Comment by joepal1976** [comment]
It seems that some targets cannot be found, which is strange. Until I've figured out that issue, I've made a minor fix so that it does at least not crash if a target listed in the MHM cannot be found. 

Regarding the mick MHM file, it now imports, but three modifications are dropped. 

I'll take a further look at why this happens in the next few days.

**Comment by Iansamit** [comment]
Thanks Joel. I forgot to mention that this may be another Blender 3.0 issue - I'm fairly sure that this was working in 2.9. 

It also may be relevant that my .mhm files are stored inside my Blender project directory rather than the standard ...v1py3/models directory.

**Comment by joepal1976** [comment]
At some point, MPFB is probably going to start to require 3.0, as I'm eyeing geometry nodes for a few solutions. Thus I'm mostly developing for 3.0 now, and only occasionally testing for 2.9. 

But in this case it should not matter. And for MHM, it should be able to interpolate target locations irregardless of where the MHM file is located. 

Anyway, thank you for your testing and your test reports. This is exactly what is needed at this point.

**Comment by joepal1976** [comment]
I think I found what was wrong now. There was a comma sign missing in the list of opposing targets. 

Can you check if things seem to work now, and take an especially hard look at whether the "eyefold" targets seem to have been applied as expected in the MHM import?

**Comment by Iansamit** [comment]
It's not giving an error message now, but the models are still not importing correctly. No need to look at eyefold details, these side-by-side comparisons of "Import Human" (left) and "Import mhm" show the problems fairly clearly.

Most clothes are missing from the "import mhm" model as well as hair. Strangely enough, there are shoes on that model that are not visible in MakeHuman. Perhaps they were there once and MH didn't remove them completely from the mhm file. The eyes and teeth are also not correctly aligned with the body or rig.

![mhm_import_bug_02_keef_body](https://user-images.githubusercontent.com/5831121/149805567-5eb17b03-dca1-41bc-b073-27e5c6544a52.png)

Here, I have removed the hair from the "Import human" model, and brought the camera in to show the difference in model height. 
![mhm_import_bug_02_keef_height](https://user-images.githubusercontent.com/5831121/149805618-64367238-aded-4a3b-a8a9-8cd3475444d8.png)

In this comparison, the mode height difference is even more obvious, and the "Import mhm" model's feet are missing. Also, the model has shoes that don't exist in the current version.
![mhm_import_bug_02_kaylee](https://user-images.githubusercontent.com/5831121/149805604-6550cfb1-fc2c-4745-89f6-bd98dc5552b7.png)

I am also attaching the two mhm files. I hope this is useful
[Kaylee.txt](https://github.com/makehumancommunity/mpfb2/files/7883551/Kaylee.txt)
[Keef.txt](https://github.com/makehumancommunity/mpfb2/files/7883552/Keef.txt)

**Comment by joepal1976** [comment]
I think one problem here was a unicode decode error in a clothes asset. Having fixed this, the characters now look reasonably similar to the left hand versions in your images when I import them. 

There is still the problem with the MHM parsing routine sometimes guessing wrong when trying to match clothes and hair settings against actual files. 

Can you take another look at how it looks on your side and list what differences/strangesnesses you still see?

**Comment by Iansamit** [comment]
Yes, I should have thought of that. Most of the clothes I was importing are community assets, which can be problematic. I tried deleting all assets from the models before importing them. I don't think it changed anything, even after updating the plugin, but the problem becomes clearer. Notice that the rigging does not align correctly with the bodies:

![mhm_import_bug_02_kaylee_03](https://user-images.githubusercontent.com/5831121/149964508-268ded04-46bb-4b62-af60-b8f83211a429.png)
![mhm_import_bug_02_keef_height_03](https://user-images.githubusercontent.com/5831121/149964525-5e46ede5-2ae5-48dd-b8d5-4d3b51c096b9.png)

Fortunately, after deleting the rig and re-rigging, they do align correctly:
![mhm_import_bug_02_re-rigged](https://user-images.githubusercontent.com/5831121/149965888-a5707031-41f9-4757-b254-d50c1f58dc11.png)

**Comment by Iansamit** [comment]
Here are some other observations:

1. "Import mhm" imports the standard rig regardless of settings saved from MH.
2. Regardless of whether "Place feet on ground" is selected in "importer presets", the model's origin is placed at 0-0-0
3. For the rigify rig, the IK bones seem to be the main problem. FK bones do not distort the mesh, although the mesh does not follow them exactly.
4. The other rigs seem to work fine if the initial rigging is deleted and the model re-rigged - even using the IK "Rig helpers" for the default rig.
5. The model takes a much longer time to load than previously, and much longer than the regular MH import.

That's all I can think of for now.

**Comment by Iansamit** [comment]
Here are some other observations:

1. "Import mhm" imports the standard rig regardless of settings saved from MH.
2. Regardless of whether "Place feet on ground" is selected in "importer presets", the model's origin is placed at 0-0-0
3. For the rigify rig, the IK bones seem to be the main problem. FK bones do not distort the mesh, although the mesh does not follow them exactly.
4. The other rigs seem to work fine if the initial rigging is deleted and the model re-rigged - even using the IK "Rig helpers" for the default rig.
5. The model takes a much longer time to load than previously, and much longer than the regular MH import.

That's all I can think of for now.

**Comment by joepal1976** [comment]
Ok, seems I'll have to re-visit the entire MHM procedure. I had only developed and tested it against a few simple test scenarios. 

Anyway, I'll have to remove/hide a few of these images. Not because I think there's any problem with them per se, but because chances are some automatic bot might detect them as violating some github terms. But I have downloaded them and noted their contents.

**Comment by joepal1976** [comment]
Well, the upside of all this is that I've had proper real world test data to use when hunting down performance hogs. Initially, loading Kaylee took 27 seconds on machine, mostly because of deep search for missing assets. Now it takes 7 seconds.

**Comment by joepal1976** [comment]
Also, the feet on ground and rigging seems to be more functional now:

![image](https://user-images.githubusercontent.com/10105480/150646052-31088ec1-4695-4386-a19f-507b89547db1.png)

**Comment by Iansamit** [comment]
Yes, the alignment problems have all been solved now as far as I can tell. 

Also, after replacing the standard rig with rigify, before generating the final rig, rotating/moving the meta rig bones deforms the mesh as expected. 

![mhm_import_bug_02_kaylee_05](https://user-images.githubusercontent.com/5831121/150688850-929a891a-96f8-459b-ab73-c47171bec271.png)

However, after generating the final rig, and using IK helpers, the distortion noted previously still occurs.
![mhm_import_bug_02_kaylee_06](https://user-images.githubusercontent.com/5831121/150688711-da05db20-fd4d-4d72-8a20-bd053d5cee4f.png)

Experimenting, I tried importing the model directly from MH then following the same procedure. On one try, the IK movement worked correctly, but now it's behaving the same way as the  mhm import. I will try again tomorrow to see if I can duplicate the correct behaviour. 

Anyway, since the remaining problems are all rigify related, and since importing directly from MH causes the same distortion, perhaps this issue should be closed and the remaining problems moved over to #21.

**Comment by joepal1976** [comment]
The same thing does not happen when creating a model from scratch and applying rigify. As far as I can see, everything then works as expected:

![image](https://user-images.githubusercontent.com/10105480/150809812-e7f31cf5-d3c9-4374-8b52-033b3383332a.png)

I'll keep this issue open a while longer to figure out why it works with a model created from scratch, but not with a model imported via MHM.

**Comment by Iansamit** [comment]
Thanks - I will try with a model from scratch. Perhaps it's an issue with my hardware or system.

**Comment by Iansamit** [comment]
Aha! The rigify distortion is definitely limited to "Import MHM" and while experimenting, I found a temporary work-around for my own workflow.

1. I tried making a model from scratch and rigify worked as expected.
2. So then, just to check, I saved a copy of the MH default, imported that via "Import MHM" and found the same strange distortion as my models showed.
3. I then tried saving the mesh from that model  as a preset via "Manage presets", created a new model from that preset, rigged it, and there was no distortion.
4. Finally, I did the same thing with one of my models and also found no distortion.

I haven't tried adding assets to the model yet and it's getting late, so I will leave that until tomorrow.

**Comment by Iansamit** [comment]
I think we're getting closer to tracking this down - it seems to be related to importing with a skeleton.

If I import a model from MH with no skeleton, then add the rigify rig, rigify IK works as expected. However, importing from MH with a skeleton (so far I've tried both the standard MH and CMU), deleting that rig, then adding rigify results in the distortion.

I guess this is why the problem was always occurring with "Import MHM" but only sometimes importing from MH - "Import MHM" always comes with the default rig, regardless of settings or whether the model had a skeleton when the .mhm file was saved.

I thought this might have something to do with weight painting, but I've been comparing the vertex groups of both versions of the mesh and can't find a difference so far.

**Comment by joepal1976** [comment]
Yes, my initial suspicion would also have been that the old weight painting remained when switching skeleton. But I haven't had time to test this yet.

**Comment by joepal1976** [comment]
Retesting this, it seems as if the issue has gone away after the recent rigify updates. 

I'll close this and we can re-open if similar issues resurface at some point.
