### ISSUE TITLE
MPFBv2.0a3 gives errors on "create human"

### ISSUE THREAD

**Issue by GeoffPB1** [makehumancommunity/mpfb2#200]
**Describe the bug**
Action: In Blender: "N"/ MPFBv2.0-a3/Select "From Scratch"/select a few Phenotypes.. Hit Createhuman button - Gives 2 errors: 

-The "Import-Export Wavefront OBJ format" addon seems to be disabled. You need to enable this in the preferences.
_I understand the OBJ issue was dealt with in earlier versions. there is no "Import-Export Wavefront OBJ format" to activate._

-Python: Runtime Error: class MPFB_OT_create _human, function execute: incompatible return value,: 'CANCELED' not found in ("RUNNING-MODAL', 'CANCELLED','FINISHED',PASS_THROUGH','INTERFACE')

**Checklist**
New install of windows 10 on upgraded 1TB sd M.2 slot 3/07/2024
Windows updates completed. Drivers installed. no other issues.

Blender 4.1.1 (initial install 4/07/2024.  Re-downloaded, reinstalled 10 Jul 2024. . Both installs gave the same error. (After having first verified removal of plugin on blender/restart in first install, reinstall plugin and then having same  fault )
"!" Flag on all MPFBv2a3 plugin attempts. (Pref/Add-ons) Plugin is in Alpha stage

In Blender Preferences/Addons:  MakeHuman::MPFB, 	Description: Makehuman plugin for Blender,  
 Location:    View3D>Properties 
File:   C:Users\gbull\AppData\Roaming\BlenderFoundation\Blender\4.1\Scrirpts\addons\mpfb\_init_.py,
 Author: 	JoelPalmius
Version:	2.0.3

- If you recently upgraded mpfb2, did you read http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html
                       Yes, but  I cannot/don't know how to bring up system and build info as shown on that link. see image below.
**Screenshots / logs**
- If applicable, add screenshots to help explain your problem.
- If the problem is related to blender 4, a screenshot where the panel "system and resources" is expanded - see above
- If there was a crash or if you think the logs would be useful, attach a log file. You can find a "export log" button on the "developer" panel in MPFB.

**Platform and versions**
 - OS: Is this windows, mac or linux? Win 10
 - Version of Blender 
![image](https://github.com/makehumancommunity/mpfb2/assets/175285538/28af4b89-4c5e-4f57-aad7-fe053b06c6cf)

 - Version of MPFB, preferably a link to which exact binary you downloaded. If not possible, an approximate date of when you downloaded MPFB. See above.

![image](https://github.com/makehumancommunity/mpfb2/assets/175285538/5a06b1de-e242-469d-bf79-19a64342fb22)

PC Specs:
Device name	DESKTOP-VJ0JVV7
Processor	Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz   3.00 GHz
Installed RAM	128 GB
Device ID	F7D1703C-CC02-4B65-A27D-D4158896CB1E
Product ID	00330-80000-00000-AA955
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Windows Specs: 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎07/‎2024
OS build	19045.4651
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by joepal1976** [comment]
That's because mpfb 2 alpha 3 was released before blender 4 existed. It is not compatible with blender 4+.

To use MPFB with blender 4, download a nightly build. The nightly builds are feature complete for the upcoming beta 1 release minus a few planned fixes. 

You can find download links to the nightly builds here: https://static.makehumancommunity.org/mpfb/downloads.html

**Comment by joepal1976** [comment]
By the way, I would recommend that you click the "remove" button for the alpha 3 addon in blender and then restart blender before installing the nightly build.

**Comment by GeoffPB1** [comment]
Thanks for your prompt reply Joe.  
MPFB-2.0a3 is the most recent release I can find as per the link. I dont see the nightly build pages that I remember finding from earlier visits last year....
Any browser (Firefox, Google, MS Edge) gives the same result. The Primary and Secondary mirror links are the same. 
I may have to revert to Blender 3 something if that is the most recent release.
Wondering if the links are 'broken', or do I need to use a vpn in order to see something different ? 
Confused, but hopeful.....

Kind Regards 

Geoff 
![image](https://github.com/user-attachments/assets/b52c6cdc-5fc8-4a7d-9873-f79c14515fbc)

**Comment by joepal1976** [comment]
Ah. I see that the process for the nightly builds has apparently got stuck, causing the "plugins" dir (where nightly builds are supposed to be) to be mostly empty.

Sorry, that's obviously a fault on our side.

I'll need to get access to the build server to see what has happened, but that might take a few hours. I'll post an update when it works again.

**Comment by joepal1976** [comment]
Now the nightly builds run again. You can find the mpfb build here: https://files2.makehumancommunity.org/plugins/

**Comment by GeoffPB1** [comment]
Yay
