### ISSUE TITLE
Python Runtime Error...

### ISSUE THREAD

**Issue by rambleman2033** [makehumancommunity/mpfb2#201]
Not sure what I'm doing wrong.  I followed the installation guide, installing both plugin and the system assets package.  But when attempting to create character from scratch, I'm receiving both a runtime error and an error involving the import-export wavefront plugin.  I am using Blender 4.1.1 and have the MPFB2 alpha 3 plugin installed.  Here is what the console reports:

[INFO ] uiactions ..............................: Executing MPFB_OT_CreateHumanOperator
RuntimeError: class MPFB_OT_create_human, function execute: incompatible return value , : 'CANCELED' not found in ('RUNNING_MODAL', 'CANCELLED', 'FINISHED', 'PASS_THROUGH', 'INTERFACE')
Error: The "Import-Export Wavefront OBJ format" addon seems to be disabled. You need to enable this in the preferences.
Error: Python: RuntimeError: class MPFB_OT_create_human, function execute: incompatible return value , : 'CANCELED' not found in ('RUNNING_MODAL', 'CANCELLED', 'FINISHED', 'PASS_THROUGH', 'INTERFACE')

Any help would be appreciated. Thank you.

**Comment by joepal1976** [comment]
Is it possible that this is the same as #200, ie that you did not find the nightly build and instead installed the old alpha 3 release?

The quick summary is that alpha 3 is not blender 4 compatible. You need to run a recent nightly build when using blender 4.
