### ISSUE TITLE
Can't save preset

### ISSUE THREAD

**Issue by Vidyut** [makehumancommunity/mpfb2#203]
**Describe the bug**
Shaped the model according to the sliders. Tried to save the preset. Can't.

**Checklist**
- If you are using blender 4, did you use the blender 4 specific build? 4.1.1
- If you recently upgraded mpfb2, did you read http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html yes, I think I have the right version

**Screenshots / logs**
![image](https://github.com/user-attachments/assets/e25738fa-f149-4cc2-bd26-f81a7af1c16b)

**Platform and versions**
 - OS: Is this windows, mac or linux? Ubuntu 24.04
 - Version of Blender 4.1.1
 - Version of MPFB, preferably a link to which exact binary you downloaded. If not possible, an approximate date of when you downloaded MPFB. Couple of days ago? I download the "latest" one, so the link will have changed.

**Comment by joepal1976** [comment]
Thanks. Yes, I see that's something I messed up the last few days, when I worked with support for the "game engine" material.

It should not be hard to fix, once I get time to open my developer computer.

**Comment by joepal1976** [comment]
I've pushed a fix. It's in master now or in tomorrow's nightly build. 

Maybe you can test if it solves the issue?

**Comment by Vidyut** [comment]
Tested. Works now.

**Comment by Vidyut** [comment]
This issue can be closed.
