### ISSUE TITLE
Weird root bone values for game engine rig

### ISSUE THREAD

**Issue by spamrakuen** [makehumancommunity/mpfb2#215]
**Describe the bug**
Default root bone values are werid. 

**Checklist**
- I'm using Blender 4.2 + a quite recent nightly build.

**Screenshots / logs**
- First I create a new human from scratch
- Then I add a "game engine" rig
- Root bone has strange head, tail and roll values. I can change them in edit mode without issues, so it's not a big deal. But default values are useless and can be a problem inside my game if I want to use that bone position for something.

IMHO bone head should be at 0,0,0 and tail something like 0, 0.05, 0 with roll = 0

**Platform and versions**
 - OS: Win10
 - Version of Blender: 4.2
 - Version of MPFB: a few days ago.

**Comment by joepal1976** [comment]
@spamrakuen I've pushed https://github.com/makehumancommunity/mpfb2/commit/cba2a82e313a81e3769a0d9dac5dfe85dbde9d3a for this. Can you check if it is an improvement? It'll be available from tomorrows nightly build or from git now.

**Comment by joepal1976** [comment]
Assumed to be good enough

**Comment by spamrakuen** [comment]
Its working now, thanks.
