### ISSUE TITLE
Python Runtime Error on blender 4.4.0

### ISSUE THREAD

**Issue by Reikott** [makehumancommunity/mpfb2#217]
**Describe the bug**
Trying to generate a human model from scratch results in a Python Runtime Error.

**Checklist**
- If you are using blender 4, did you use the blender 4 specific build? YES
- If you recently upgraded mpfb2, did you read http://static.makehumancommunity.org/mpfb/faq/ensure_correct_version.html ALSO YES

**Screenshots / logs**
bpy.ops.mpfb.create_human()
Python: RuntimeError: could not create instance of MPFB_OT_create_human to call callback function execute

**Platform and versions**
 - OS: Linux (NixOS 24.11.20241105.4aa3656 (Vicuna) x86_64)
 - Version of Blender: 4.4.0 Alpha
 - Version of MPFB: 20241107

**Comment by joepal1976** [comment]
I see this is on an alpha version of blender. Does it work for you on 4.3.0? 

I haven't yet looked into what changes are required for 4.4.0 since 4.3.0 isn't released yet.

**Comment by Reikott** [comment]
I did find a similar issue reported on the blender bug report page:
https://projects.blender.org/blender/blender/issues/129699

**Comment by joepal1976** [comment]
Thanks for the info. Obviously, the idea is that it should work on 4.4.0 too, but fixing it might be a few days down the todo list.

**Comment by joepal1976** [comment]
Note to self: Check if docs on python update at https://developer.blender.org/docs/release_notes/4.4/python_api/ are relevant for this issue.

**Comment by joepal1976** [comment]
I've now made a fix which I think should make the code mostly blender 4.4.0 compatible. 

Help with testing would be welcome.

**Comment by Reikott** [comment]
So. I installed the new version. So far so good.

Now it no longer throws a Python Runtime Error. The human models generate just fine.

The other settings work as well. No issues when it comes to changing the parameters (like age, height, muscles etc).

Rigs also work great. No issue in this area from what I can see. I can also generate a Rigify rig just fine.

Same with assets. They all seem to work. Although I haven't tested every asset. But the ones that I tried work.

**Comment by Reikott** [comment]
If there are any specific tests you'd like me to do please tell me. But from what I can see everything seems to work.

**Comment by joepal1976** [comment]
Thanks. Clicking around on a few buttons to see what happens is exactly what was needed. I currently don't have any indication that anything else is broken, but I haven't really started using 4.4.0 yet. 

One area that is traditionally fragile is materials. Again, I have no reason to think that they are broken, but if you happen to notice that something looks off, then it might be due to changes in shader nodes.

But I'll close this issue as fixed.
