### ISSUE TITLE
new obj importer

### ISSUE THREAD

**Issue by ekswathi** [makehumancommunity/mpfb2#22]
Blender 3 and new have a new obj importer.  The existing importer is used in mpfb2 as I understand.  But blender website says the existing importer will be removed soon.  The new importer is not working for mpfb2.

**Comment by joepal1976** [comment]
The obj importer works fine in blender 3.1.0-beta though. 

Do you happen to have a link with more information about the importer changes?

**Comment by ekswathi** [comment]
If we enable old importer it will work.  But It can make confusion.  And Most probably they will remove it in newer releases.

**Comment by ekswathi** [comment]
I will checkout and let you know

**Comment by joepal1976** [comment]
With blender 3.2, the obj importer still works as expected. 

I'll close this. We can revisit as and when it seems as if it'd be a problem.
