### ISSUE TITLE
The MPFB2 port of MakeClothes doesn't really work, should be hidden from the UI until actually implemented

### ISSUE THREAD

**Issue by TACarp** [makehumancommunity/mpfb2#23]
I am not sure if this is a bug or user error. I am trying to create a clothes file for MakeHuman in blender. Here are the steps I took with break when problems began.
1) I installed the latest addon version in blender 2.93.8
2) I loaded my human MHM file.
3) I extracted a helper skirt and marked it as clothes.
4) I modeled from the helper skirt.
5) I filled out the clothes metadata and pressed, "Write Clothes."
//Problem//
6) The blender file browser opened and asked me to save as a blend file, which I did.
7) I checked "C:\Users\troyc\Documents\makehuman\v1py3\data\clothes" and did not see the folder for what I had created. I also checked "C:\Users\troyc\AppData\Local\makehuman-community\makehuman\data\clothes" and did not see it.
6) I pressed write clothes again and it asked me to save as a MHCLO file.
7) I named the file and saved it in a temp folder on my C: drive, thinking, if it saved as a MHCLO, then I would move it to my MH data directory. This was odd to me as in the past MH clothes creation created a whole folder with image textures, OBJ, and MHMAT files.
8) I checked the temp folder and no MHCLO file or the other files were there. I then checked the two data directories I know about. (off topic: is it user error to have two? Which one should I keep?) There was no folder with the item I had created.

Is this user error? I couldn't find documentation on this process, which is understandable given how much time it would take to create complete documentation for this addon given that it is being changed often. If this is user error please advise. If this is a bug please mark this issue as a bug report. Thanks in advance.

**Comment by joepal1976** [comment]
This is a lack of documentation. The MakeClothes port in MPFB2 is far from complete, as in most functionality not even present. But the only indication you get of this is a label in the UI:

![mpfb_mc](https://user-images.githubusercontent.com/10105480/154303681-d4a359d8-9b2d-4605-b752-2b8e346387e9.png)

For now, your only option is to use the standalone MakeClothes, https://github.com/makehumancommunity/community-plugins-makeclothes, which will be available in a separate tab.

I really should hide the MakeClothes panel in MPFB until it actually does what it says it should do.

**Comment by joepal1976** [comment]
As a side note I'm working on what is to become the release notes for MPFB 2.0-alpha1, at http://static.makehumancommunity.org/mpfb/releases/release_20a1.html

I'm not going to be able to finish porting MakeClothes before that release, so it's now listed under "known issues". 

If you happen to find more stuff like this, I appreciate the head's up so I can make the UI more clear or at least provide some docs explaining the behavior.

**Comment by joepal1976** [comment]
Closing handled issues with no additional info for a month
