### ISSUE TITLE
Purple textures when rendering

### ISSUE THREAD

**Issue by Victor1266** [makehumancommunity/mpfb2#26]
After applying assets render and shading preview gives purple color:

![image](https://user-images.githubusercontent.com/18232879/162950579-cc60a2d8-b13e-4f18-8418-7392bc5ef3a4.png)

But in shading view this looks normal:

![image](https://user-images.githubusercontent.com/18232879/162950974-14bf678a-814e-4bc4-a34b-daa9f5715c45.png)

This happened after I moved to Blender 3.1. And updated the mpfb2 to alpha version from website. What can cause this issue? 

The problem persist both on eevee render and cycles render.

**Comment by shubhampatilart** [comment]
Check World setting this look like world texture is missing

**Comment by Victor1266** [comment]
Thank you! That resolved my issue
