### ISSUE TITLE
Human Mesh and Snap to Cursor / Vertex Coordinate Issue 

### ISSUE THREAD

**Issue by OfAllTheBars** [makehumancommunity/mpfb2#29]
Firstly, thanks for creating the plug-in.  For an alpha release it seems to work quite well,

I've noticed an odd issue where the generate mesh coordinates appear to be 'off'.  To explain...

1. I created a default human (New Human > Create Human having not changed any settings.). 
2. In edit mode I select any (single) vertex
3. I use Snap Cursor to Selected (Shift + S > 2)

The cursor is, however, not placed on the vertex, ALTHOUGH, the vertex coordinates (as shown under the Item draw tab), and the 3D cursor coordinates (as shown under the View tab) do actually match.  (Screen shots below.)  The same behaviour is shown if edge loops are selected.

Orthogonal front view:
![image](https://user-images.githubusercontent.com/16051751/164711448-3adf140b-e61a-4753-a6e4-78cf8255e336.png)

Orthogonal side view:
![image](https://user-images.githubusercontent.com/16051751/164711627-d7e8800d-3112-4452-a77e-0c130df5b3b7.png)

Item (i.e. selected vertex) position (local and global):
![image](https://user-images.githubusercontent.com/16051751/164711935-deefd1d6-0abc-4074-a445-5f6003073542.png)
![image](https://user-images.githubusercontent.com/16051751/164711905-0de8accd-0fb8-4b8c-bd1f-83cf3155ff2a.png)

3D Cursor position:
![image](https://user-images.githubusercontent.com/16051751/164712061-1317e386-7367-4d1e-bbbb-0274a52f054d.png)

Using MPFB version 2.0.1 -a1
Blender 3.1.0
Log file (in DEBUG mode) attached.  I hope I got the right one.

[combined.txt](https://github.com/makehumancommunity/mpfb2/files/8540889/combined.txt)

And to check my own sanity I followed the same 3 steps as above but with a cube and it works as expected.
![image](https://user-images.githubusercontent.com/16051751/164713082-4297550a-4b17-407d-accb-74a306fe0605.png)

Finally, I performed the same operations on an human created with MakeHuman standalone, followed the same steps and, again it works as expected.
![image](https://user-images.githubusercontent.com/16051751/164713589-0a3d3905-203e-4b84-bff3-b67a38c60db2.png)

PS I discovered the problem whilst trying to manually add a Rigify rig. 
PPS As far as I can see there is no unapplied scaling on the model that might account for the issue.

**Comment by OfAllTheBars** [comment]
If I turn off the Human mesh "(Apply) Shape Key (in) Edit Mode" button (see image), then the behaviour is correct (i.e. select a vertex, snap the 3d cursor to selected... does place the cursor on the vertex) but of course the mesh is then the wrong shape.  I need to read up on shape keys to understand them better.  Also this might actually be a Blender bug (i.e. Snap cursor to selected ignores active shape keys).

**Comment by OfAllTheBars** [comment]
Ok.  If I understand things correctly this might be a MPFB2 feature rather than bug.  Basically, as shape keys are used for the modelling, if a user wants to safely edit or sculpt the generated human mesh they should "bake" the shape keys first. Of course this then prevents any further changes being applied via MPFB2 as it will change or remove any edits/sculpts.  There is a method to "bake" shape keys (although no bake shape key function in Blender). 

So, I guess you could close this as a MPFB2 bug, although perhaps there could be a feature request for a "Remove Shape Keys" button (with all the relevant warnings) and probably also a button to "Remove Helper Geometry" as that must also get broken by any editing or sculpting.

I am happy to write a documentation page about this, the method to "bake" shape keys, and the up- and down-sides of doing so - just let me know.

Also, sorry for not getting to the root of the non-problem before I raised the issue.  As always, Blender is entirely logical in what it does if not intuitive.

**Comment by joepal1976** [comment]
Yes, edit mode behavior might be somewhat unintuitive when there are shape keys. 

Providing a GUI button for baking the resulting mesh from shape keys should not be dramatically difficult though. This is already done as an intermediary step in some clothes fitting calculations. 

I'm thinking a new panel looking something like:

```
Bake shape keys
[X] Bake to new instance of mesh (rather than destroying shape keys on selected)
[X] Bake proxymesh rather than basemesh if available
```

Maybe you have further suggestions on what would be helpful.

But regardless of this, documentation is always a good thing. If you want to help out with writing docs, this would be very helpful.

There are instructions for how to help with docs at http://static.makehumancommunity.org/contributing/help_edit_this_site.html

**Comment by joepal1976** [comment]
I think this is solved by the addition of the button for baking shape keys.

**Comment by OfAllTheBars** [comment]
Correct. This is solved.
