### ISSUE TITLE
Converting "Game base" rig to Rigify results in twisted foot

### ISSUE THREAD

**Issue by grascm** [makehumancommunity/mpfb2#30]
Steps to reproduce:
1. Create human from scratch
2. Add standard "Game engine" rig
3. Convert to rigify (with produce enabled)
<img width="324" alt="Screenshot 2022-05-13 at 15 39 20" src="https://user-images.githubusercontent.com/12994709/168285674-325efc51-b3c6-450e-9a2a-a2708dfb7881.png">

Control `foot_tweak_l.001` appears to be rotated by 90 degrees for some reason.

UPD: MPFB version from latest commit on master branch, Blender 3.1

**Comment by grascm** [comment]
After some research i figured out that, the issue seems to be in rigify itself.
This project, however, can have a workaround.
There are several options.

#### The simplest
Apply rest pose as current pose, as a final step of generation. For some reason current and rest pose have difference, and the rest pose doesn't have issues.

#### More correct solution
I suggest using `limbs.leg` instead of `limbs.paw` when generating rigify metadata.
It generates different deformation bones, and the issue is not relevant anymore
<img width="441" alt="Screenshot 2022-05-14 at 17 57 19" src="https://user-images.githubusercontent.com/12994709/168433216-48ae5592-a93f-4c24-bab5-35ab8c8d5dd2.png">
(the first (closest) leg is `limbs.paw`, the second is `limbs.leg`)

Also it has more convenient IK controls, for leg animation.

Rigify requires additional heel bone, for IK control placement, it can be generated dynamically.
If this solution is OK for the project, i guess i can implement it and make a PR.

**Comment by joepal1976** [comment]
Thank you for the suggestion. 

As far as possible, MPFB2 should handle these kind of issues. So I'm putting it on the to do list.

**Comment by michaeltyers** [comment]
Hi,

I'm currently using Blender 3.3 and version 2.0.1 of the MakeHuman Plugin for Blender.

![image](https://user-images.githubusercontent.com/52456613/190601776-78d57670-b150-46ef-a818-ac80c75537df.png)

I downloaded and installed this version of Blender and MPFB last night.

![image](https://user-images.githubusercontent.com/52456613/190601914-523e05a1-9bfe-48b4-a2b0-cbc2d8db5ca2.png)

Issue still persists.

![image](https://user-images.githubusercontent.com/52456613/190602181-2a81dbb6-b14f-409f-aa9b-781494b32e14.png)

Applying as rest pose does fix the issue.

**Comment by joepal1976** [comment]
The 2.0.1 stamp in the preferences is a misnomer, it's actually 2.0.0-alpha1. Alpha 1 was released in march, ie four months before the issue was fixed. 

Can you try downloading the latest build from https://download.tuxfamily.org/makehuman/plugins/ and see if this fixes the issue for you?

**Comment by michaeltyers** [comment]
Hey @joepal1976,

Thank's heaps for your assistance. I thought I was downloading the latest version but clearly not - they just had similar names.

Appreciate the assistance.


Mike
