### ISSUE TITLE
How can I import bvh animation file?

### ISSUE THREAD

**Issue by mrParabol** [makehumancommunity/mpfb2#33]
How can I import bvh animation file? When I import the bvh animation file, the animation does not work.Thanks in advance for your interest.

**Comment by joepal1976** [comment]
Support for BVH animations and poses (ie makehuman style poses) have not been implemented in MPFB2 yet. 

You could, however, take a look at "BVH retargeter", http://diffeomorphic.blogspot.com/p/bvh-retargeter.html

Maybe this might solve your problem?

**Comment by joepal1976** [comment]
Closing handled issues with no additional info for a month
