### ISSUE TITLE
Assets not appearing

### ISSUE THREAD

**Issue by TheMineCommander** [makehumancommunity/mpfb2#35]
I have opened Blender, imported the .zip file into the addons, imported the zip again into the assets, and restarted Blender. Then, when I create a human, it does not let me use assets because of this:
![image](https://user-images.githubusercontent.com/67017088/172956450-cb7ce886-47b2-4e1a-9a52-d807971ad617.png)
Is this a problem with the zip or am I just an idiot? How do I fix this?

**Comment by OfAllTheBars** [comment]
From your description sounds like you imported the same ZIP file for the plugin and the assets.  The assets should be downloaded from [here](https://download.tuxfamily.org/makehuman/asset_packs/index.html). (See [Getting Started](http://static.makehumancommunity.org/mpfb/docs/getting_started.html) page.)

**Comment by TheMineCommander** [comment]
I see those, but I still have a problem: how can I download the assets?

**Comment by OfAllTheBars** [comment]
Let me know if this helps...

Scroll to the bottom of the [assets download page](https://download.tuxfamily.org/makehuman/asset_packs/index.html) and select one (for example Hair_01).
![image](https://user-images.githubusercontent.com/16051751/173177977-4293c058-b272-45c7-8210-2d9e21a71997.png)

Then click the link to the .zip file. (They are usually at the top of the page I believe).
![image](https://user-images.githubusercontent.com/16051751/173178016-da1d3796-4675-43fa-bcf7-956adf3072a4.png)

**Comment by TheMineCommander** [comment]
Got it. Thank you!

**Comment by joepal1976** [comment]
Closing handled issues with no additional info for a month
