### ISSUE TITLE
Need an easy way to bake all shapekeys and/or delete helpers

### ISSUE THREAD

**Issue by LainIwakura98** [makehumancommunity/mpfb2#37]
A garbage mash is created when a character is created from scratch
![изображение](https://user-images.githubusercontent.com/39774833/176899419-cc9ef47d-3637-41de-b504-473d4b9b2255.png)

**Platform and versions**
 - OS:  windows
 - Version of Blender - 3.2.1
 - Version of MPFB - last build 2.0.1 from 01.07.2022
Can I create a character without this and the modifier that hides it?

**Comment by joepal1976** [comment]
![apply_helpers](https://user-images.githubusercontent.com/10105480/176912797-e2c15e49-48bc-435d-9d1c-6661adb8c512.png)

**Comment by LainIwakura98** [comment]
Thanks! But shape keys does not allow to apply a modifier, how to save all shape keys in basic and accept?

**Comment by joepal1976** [comment]
Providing a one-click-button solution for baking shape keys and/or deleting helpers is on the todo list. But for now, there is a workaround by using the sculpt operation panel:

![apply_helpers_2](https://user-images.githubusercontent.com/10105480/176919257-d465863b-bb05-4cdc-a5e5-ac7b1cd0d151.png)

This will bake all shapekeys and also delete helpers, so it will basically do both steps for you.

I fully understand that this workaround might seem obscure, so I'll prioritize adding more accessible functionality for it.
