### ISSUE TITLE
Prepare for having multiple rigify type rigs

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#43]
While at the moment there is only one rigify meta-rig included in MPFB, it is perfectly possible that we would want to have multiple such rigs in the future. This akin to default / default-no-toes for the standard rigs.

We should prepare for a future where there might be multiple included rigify rigs.

**Comment by angavrilov** [comment]
Pull request #57 adds a toes Rigify rig.

**Comment by joepal1976** [comment]
Thanks. I'm going to consider this addressed with the change.
