### ISSUE TITLE
Errors and warning in the debug build of Blender

### ISSUE THREAD

**Issue by angavrilov** [makehumancommunity/mpfb2#44]
Loading the add-on in the debug build of blender produces many errors and warnings. Some examples:

> WARN (rna.define): C:\Blender\Source\blender\source\blender\makesrna\intern\rna_define.c:1647 RNA_def_property_ui_text: 'The cup size of the breasts. On male characters, anything but 0.5 will look strange.' description from 'MPFB_HUM_cupsize' '' ends with a '.' !

> ERROR (rna.define): C:\Blender\Source\blender\source\blender\makesrna\intern\rna_define.c:1296 RNA_def_property: runtime property identifier "Scene.arms.l-lowerarm-scale-depth-decr-incr" - one of the characters failed an isalnum() check and is not an underscore

> Registering panel class: 'MPFB_PT_Macro_Sub_Panel' misses category, please update the script

A copy of the full list can be found here:

https://pastebin.com/BdDExjRW

**Comment by joepal1976** [comment]
Where can I find the debug build of blender? Running the 3.3.0 beta with "--debug-all" does not seem to provide these messages.

**Comment by angavrilov** [comment]
I just compile it. Debug build means un-optimized build with extra checks and assertions.

**Comment by joepal1976** [comment]
Closing as fixed. The one remaining warning will be removed separately when the teeth rigify option is removed.
