### ISSUE TITLE
Rigify Rig face bone is not in the center

### ISSUE THREAD

**Issue by shubhampatilart** [makehumancommunity/mpfb2#48]
**Describe the bug**
Rigify Rig face bone is not in the center

**Screenshots / logs**

Normal
![HSP 3 2](https://user-images.githubusercontent.com/57253638/185746443-2ed03673-c0ea-4e6e-ab92-280947003d30.png)

After did Some sculpturing and morphing
![HSP 3](https://user-images.githubusercontent.com/57253638/185746250-7fa992fb-9570-4628-bdcc-dd3dc4e5ae1a.png)

**Platform and versions**
 - OS: Is this windows 
 - Version of Blender 3.2.2
 - Version of MPFB 20 Aug 22

**Comment by shubhampatilart** [comment]
How makehuman System decide where it will add this main face bone?

**Comment by joepal1976** [comment]
To be clear: is the problem that the bone is in the wrong position for an unmodified default character? Or that the bone is uncentered after you continued modeling the character?

The positions of the bones are mainly calculated via joint cubes, but also through vertex matching. There is a description at http://static.makehumancommunity.org/mpfb/developer/rigging_and_posing.html

If you change the body manually, you will also need to move the joint cubes to a corresponding position. The joint cubes can be seen by flipping or disabling the mask modifier on the human mesh.

If you only changed the character by modifying modeling targets, there is a button for refitting assets and skeleton on the modeling tab.

**Comment by shubhampatilart** [comment]
With unmodified default character face bone is slightly left side as in1st screenshot


It's easy fix by snapping to center with 3d courser but for new users they might miss this.

**Comment by joepal1976** [comment]
I can confirm that the bone tail is uncentered (x = -0.001632). The bone head seems to be correct (x = 0).

The fitting strategy for the tail is MEAN, in lines 5454 - 5465 in the definition file:

```
        "tail": {
            "default_position": [
                -0.0016322489827871323,
                -0.04190564155578613,
                1.5864936113357544
            ],
            "strategy": "MEAN",
            "vertex_indices": [
                229,
                18913
            ]
        },
```

The tail should obviously be at x = 0 too, so I'll continue by seeing if there can be a better fitting strategy for it.

**Comment by joepal1976** [comment]
Theoretically, vertices 1008, 7702 could be a better fit. But I'm uncertain if there are unwanted side-effects.

@angavrilov do you have any input on this?

**Comment by angavrilov** [comment]
@joepal1976 My suggestion is either use extended MEAN from joint cubes (see above) or just the two joints so the bone overlaps the head bone. It doesn't affect anything anyway.

**Comment by joepal1976** [comment]
Having tested @angavrilov 's PR, I think that solves the problem.

**Comment by shubhampatilart** [comment]
Yes It's Solve, Thank you Alexander Gavrilov & Joel Palmius 👌👍
