### ISSUE TITLE
Missing gental mesh

### ISSUE THREAD

**Issue by 12D687** [makehumancommunity/mpfb2#52]
It seems that you can't generate genitals in mpfb2. Why so?

**Comment by 12D687** [comment]
sorry spelling mistake it's missing genital mesh

**Comment by joepal1976** [comment]
There is no difference between MH and MPFB in this regard. There are a lot of assets which are not included with the default distribution: clothes, body parts, materials and so on. One category of assets which is an optional download is genital meshes.

Genitals are implemented via proxy meshes. There are several alternative options for these in the repositories, see list of proxies at http://www.makehumancommunity.org/proxies.html

At the moment it is somewhat cumbersome to download a single asset for MPFB2, but basically you have download all files tied to it and place them in a subdirectory under data. 

* Find the data directory. There is a button "user files" under "system and resources" -> "directories" which will open a file browser. There you should find the data directory.
* In the data directory there should be a directory called "proxymeshes". If it does not exist, you can create it.
* In the proxymeshes directory there should be a subdirectory with a unique name, for example the name of the asset you want to download
* In that subdirectory you should save all files belonging to the particular asset. Make sure they get the correct file extension
* Restart blender. Now the new proxymesh should be possible to choose in the apply asset panel.

Reading this I realize it definitely is an area of improvement. It shouldn't be this cumbersome to download a single asset...
