### ISSUE TITLE
Rigs

### ISSUE THREAD

**Issue by 12D687** [makehumancommunity/mpfb2#56]
I wonder if you can use other rigs (e.g MH rigs from http://www.makehumancommunity.org/rigs.html) in mpfb2?

**Comment by joepal1976** [comment]
Yes and no, but currently mostly no. 

- No: you cannot use them right  away, and it is cumbersome to use them even after converting
- The small "yes": There are tools on the developer panel for converting an imported rig to a JSON structure usable in MPFB, and other buttons for loading and applying an already converted custom rig. These tools are mostly for internal use for developers though, and might be percieved as somewhat mysterious to casual users.

There is an issue for improving this toolset at https://github.com/makehumancommunity/mpfb2/issues/42

If you really want to use a third part rig, there is a workaround. You can create your character in MakeHuman and assign the rig there. Then you can use the "from makehuman" strategy under "new human" for importing the character into MPFB. Not all MPFB functionality will be possible to use on this character, but you should be able to equip clothes for example.
