### ISSUE TITLE
Crash when trying to save rigify meta pose

### ISSUE THREAD

**Issue by 12D687** [makehumancommunity/mpfb2#58]
I have two things
First. I got this error when I try to save my pose
Python: Traceback (most recent call last):
  File "/home/username/.config/blender/3.2/scripts/addons/mpfb/ui/applypose/operators/loadpose.py", line 57, in execute
    with open(absolute_file_path, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.config/blender/3.2/mpfb/data/poses/rigify_meta_fk/.json'

Second I'm wondering if you can use the makehuman poses (http://www.makehumancommunity.org/poses.html) in mpfb2?

**Comment by joepal1976** [comment]
Thanks, yes I can see how that can happen after a recent change. I'm on it, but it might take a few days before the fix to get in. 

As a workaround, you can manually create the /home/username/.config/blender/3.2/mpfb/data/poses/rigify_meta_fk directory before trying to save again.

Right now you cannot use the traditional MH poses in MPFB. This is on the todo list, but the MH poses are in a very cumbersome old format which does not translate easily. If you really want an MH pose and can live with not being able to do further modeling in MPFB, the workaround is to pose in MH and then create a new human "from makehuman".

**Comment by joepal1976** [comment]
I'll leave the ability to save poses for ungenerated rigify rigs, but have added a warning as well as a few checks for whether the name is legal (both in loading and saving poses)

**Comment by joepal1976** [comment]
Assuming this now works as intended.
