### ISSUE TITLE
Import Human Can Not Select Which Human to Import

### ISSUE THREAD

**Issue by Robertocollinslazo** [makehumancommunity/mpfb2#62]
When I press the Import Human button  from New Human  from Make Human  it will import a generic mesh.  I cannot choose a human to import.

Screen Shot :     ![MPFV v2 0](https://user-images.githubusercontent.com/118080891/202585482-cac0358d-dda2-43f9-b42b-5d546af6f30b.png)

Log:  [Log.txt](https://github.com/makehumancommunity/mpfb2/files/10036649/Log.txt) Might be useful.

**Platform and versions**
OS: Windows 11

 - Version of Blender: 3.3.0
 - 
 - Version of MPFB v2.0.- (can't beyond the dash on the vertical tab)
 -  (approximate date when you downloaded it is enough) less than six months?

Cheers

**Comment by joepal1976** [comment]
"Import from makehuman" will import the human currently visible in the makehuman viewport. If the default/generic human is visible in makehuman, then that is what will be imported.

To import a specific human you can:

- Either open the human in makehuman and then do new human "from makehuman"
- Or use "from presets" -> "import mhm" and open the human save file

**Comment by Robertocollinslazo** [comment]
Thank you. Got it
