### ISSUE TITLE
The addon cannot find the material assets etc

### ISSUE THREAD

**Issue by enzyme69** [makehumancommunity/mpfb2#66]
**Describe the bug**
Can't find the assets system default, eventhough the zip is installed.

**Screenshots / logs**
<img width="773" alt="Screenshot 2022-12-15 at 1 05 50 am" src="https://user-images.githubusercontent.com/3952687/207616280-e261ed8a-dc21-4ff8-aac0-057997106a3f.png">

If there was a crash or if you think the logs would be useful, attach a log file. You can find a "export log" button on the "developer" panel in MPFB.

**Platform and versions**
 - OS: macOS Ventura
 - Version of Blender 3.5
 - Version of MPFB 15 December 2022

**Comment by joepal1976** [comment]
This looks very strange. There should not be a "makehuman_system_assets_cc0" subdir. The clothes, eyebrows, eyelashes etc subdirs should be directly under data. 

Did you install the zip via the button under library settings?

**Comment by joepal1976** [comment]
No more information for a month. Closing issue. Reopen if still a problem.
