### ISSUE TITLE
Ability to delete helpers but keep shapekeys

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#72]
There are circumstance when you are a) hindered by helpers, but b) in need of target shape keys. This might, for example, be relevant when you want to export a character to a game engine where you want to use the shape keys.

There is already a "delete helpers" button under operations -> basemesh. There should be an option there if shape keys should be kept (or, as it were, reapplied from the target stack once the helper geometry has been removed)

**Comment by joepal1976** [comment]
Actually, just keep the shape keys when clicking the delete helpers button. If you don't want them, simply click bake shape keys as step 2.

**Comment by matt-borgelt** [comment]
Hi Joel, does this mean there is already a way to delete helpers, but keep the shapekeys? I have 2.0.3. Let me know if I can test this or help in any way. I posted on http://www.makehumancommunity.org/forum/viewtopic.php?f=22&t=20470&p=57002#p57002

**Comment by joepal1976** [comment]
The improvement has been pushed to the code, yes. If you download a new nightly build, you will find it under the operations -> basemesh panel.

**Comment by joepal1976** [comment]
Btw, I added a comment about the fix in http://www.makehumancommunity.org/forum/viewtopic.php?p=57005#p57005 earlier

**Comment by joepal1976** [comment]
No more comments in a few months. Assuming issue is fixed.
