### ISSUE TITLE
Breast bones don't follow chest bone correctly with rigify rig

### ISSUE THREAD

**Issue by dodopod** [makehumancommunity/mpfb2#75]
If I generate a rigify rig, and then rotate either the chest bone or spine_fk.004, the breast bones seem not to move correctly, causing the chest to warp.

With chest:![Screenshot_2023-01-02_10-32-21](https://user-images.githubusercontent.com/3210822/210258050-e364b470-b132-4b49-be00-4652c7db5828.jpg)

With spine_fk.004:
![Screenshot_2023-01-02_10-31-49](https://user-images.githubusercontent.com/3210822/210258049-b47b1dec-fc8d-4b38-88fc-2972468ce5bd.jpg)

**Comment by joepal1976** [comment]
If you take a look at the ungenerated rigify rig, you can see that the breast bones are children of spine.004 and thus follows the rotation of that 100%. 

If the breast bones were _not_ children of spine.004, the upper torso would move without moving the breast bones, resulting in different strange deformation.

I'm not saying you're wrong: obviously there is a strange deformation in the case you show. However, before doing anything about it we'd need to figure out what a better alternative would be. Breast bones children of spine.003? Something else?

If we look at the "chest" bone in the generated rig, the deformations for that seem to work as expected.

Maybe @angavrilov has an input?

**Comment by angavrilov** [comment]
Well, they happen to be located exactly between two deforms, so it's inherently difficult. Maybe the best solution is introducing yet another helper that would split the deformation of the spine bones half way and parent to that.

**Comment by joepal1976** [comment]
@dodopod Can you test if the new solution solves the problem?

**Comment by dodopod** [comment]
It's much better than it was. The pecs still warp a bit if the muscle and weight sliders are both high (and, for females, the cup size is low), and you rotate the chest bone forward more than ~15-20&deg;. It looks better if I then rotate spine_fk.004 back a few degrees.

However, I'm not sure whether it's a real problem, now. Even if muscle and weight are at 0.9 and chest is 25&deg; forward, I only notice it because I'm looking. It's only above 30&deg; where it becomes noticeable on more ordinary bodies.

**Comment by angavrilov** [comment]
@dodopod I wonder what would you be impression with these modified weights: https://www.dropbox.com/s/9jpmfwntqzq25ln/weights.human_toes.json?dl=0

I widened the influence curve of the breast bones to give them more volume to control.

**Comment by dodopod** [comment]
@angavrilov I think it's a step in the right direction, but it doesn't help all that much. What seems to work better is to increase the influence of both the breast and spine.003 bones over the bottom of the pecs.

Here's a comparison (each one is a male, with muscle and weight sliders at 1, and the chest bone canted forward by 45&deg;):

![comparison](https://user-images.githubusercontent.com/3210822/213556066-a11deeda-7a52-4ad8-a407-d9c059d98c09.jpg)

Here's my weight paint:

![Screenshot_2023-01-19_14-34-10](https://user-images.githubusercontent.com/3210822/213556082-7e4a9f73-65a2-4852-a4c4-59898e9acc43.jpg)
![Screenshot_2023-01-19_14-34-36](https://user-images.githubusercontent.com/3210822/213556090-60873e69-9c3a-44d2-bda1-cefb7a3b2f24.jpg)

**Comment by angavrilov** [comment]
My weight change isn't supposed to do anything about this problem in any case - it tries to improve deformation for proper breasts. With the original weights it feels more like moving the bone is pulling them by the nipple rather than moving the whole breast, so I made the weight fall off slower from the maximum without changing the total affected area to give it more volume.

**Comment by joepal1976** [comment]
Going to consider this solved. If needed, open separate issues for other potential weight painting issues.
