### ISSUE TITLE
Alpha 2.0.3 Alternative Materials drop-down menu doesn’t work in Windows (fixed) and issue with accents in folders

### ISSUE THREAD

**Issue by ashledombos** [makehumancommunity/mpfb2#79]
**Describe the bug**
It seems that alternative materials drop-down menu doesn’t work.

**Screenshots / logs**

See for instance the menu for male_casualsuit01
![image](https://user-images.githubusercontent.com/513335/212499381-0ef7d516-ddcf-4aee-9096-a4307203caf3.png)

The «System Clothes Material 01» and «System Hair Materials 01» packs are correctly installed.
Here, for instances, are all the casualsuit01 alternative materials by toigo (I have restarted several times Blender though it seems currently useless)
![image](https://user-images.githubusercontent.com/513335/212499450-0213b9ee-8730-4359-b114-27f17a5c7971.png)
![image](https://user-images.githubusercontent.com/513335/212499491-50d313d5-4562-433c-a74c-20098e2e4c20.png)

I have tried with several assets which should have alternative materials (hair for instance, see this screenshot)
![image](https://user-images.githubusercontent.com/513335/212500064-e18532b3-559b-4432-a611-5d2aa57d1fcc.png)

If there was a crash or if you think the logs would be useful, attach a log file. You can find a "export log" button on the "developer" panel in MPFB.

**Platform and versions**
 - OS: Is this windows, mac or linux?: Windows 10 and Linux (OpenMandriva ROME running Plasma 5)
 - Version of Blender: 3.4.1
 - Version of MPFB (approximate date when you downloaded it is enough): 2.0.3 (nightly mpfb2-20230114)

**Comment by joepal1976** [comment]
That's very odd. From your screenshots, it looks as everything is correctly installed. 

Can you also paste a screenshot of the data/packs directory?

To get anywhere with this, I'll need a log. Can you do the following?

* Go to the developer -> log levels panel
* Set the "default" level to "TRACE" (and click "set level")
* Restart blender
* Equip the casualsuit01 asset on a character
* Select the casualsuit01 mesh (so that it is selected, not only active)
* Expand the alternative materials dropdown
* Go to the developer -> export log panel and select "default"
* Click "export log" to save the log file
* Attach that log file here

**Comment by ashledombos** [comment]
Here is the screenshot of data/packs directory (I did not suppress the zip files yet)

![image](https://user-images.githubusercontent.com/513335/212702702-35c14e69-574d-4077-9809-2bdf93f11b71.png)

In case it may help, here are my settings for the add-on

![image](https://user-images.githubusercontent.com/513335/212705468-4b3a1a13-12e0-4caa-ba86-ac566b911866.png)

And the trace log is added as attachment

[logs.txt](https://github.com/makehumancommunity/mpfb2/files/10426768/logs.txt)

**Comment by joepal1976** [comment]
I can't figure out what's wrong here. There are not enough debug statements in the relevant area of the code to see what goes wrong. The output looks the same on my end, but here it works. 

I'll add some debugging to the code and make a new commit in the next few days and then ask you to re-run so I can get more info. 

I'm on it, but it might take a few days.

**Comment by joepal1976** [comment]
I've made a minor fix now. I'm not convinced that is what was wrong, but it won't hurt either. I've also added more debug statements.

The changes will appear in tomorrow's nightly build, or can be gotten from git now. 

Can you check if these changes make any difference? If not, can you do the following:

* In developer -> log levels, set "default" to "INFO"
* In developer -> log levels, set "services.assetservice" to "DEBUG"
* In system and resources -> directories click the button "log files" and delete all files in the log file directory
* Restart blender
* Create a character and equip casualsuit01
* Open the alternative materials drop down
* Go to the developer -> export log panel and select "default"
* Click "export log" to save the log file
* Attach that log file here

**Comment by ashledombos** [comment]
Hello,

I'd like to but I'm stuck at step 2:
I can't figure out how to select an entry that is outside my display area.

I have tried with the mouse wheel, the directional keys, at best I can get past it but I can't see what I am selecting.

![image](https://user-images.githubusercontent.com/513335/213583889-af2bdf31-aba7-4052-91cf-5908dc012d25.png)

Do you have an idea on how to do?

**Comment by joepal1976** [comment]
That seems difficult to solve on your end. 

I've made an additional change now, so that it is possible to filter the log channels:

![image](https://user-images.githubusercontent.com/10105480/213656554-b7e24462-8496-404f-a184-691f3234296a.png)

This will appear in tomorrows nightly build. Hopefully this will make it possible to set the appropriate debug level.

**Comment by ashledombos** [comment]
Here it is. BTW how do I use the git update instead of waiting for the next nightly to be out?
I tried downloading the zip from Github, extracting the sub-directory mpfb and recompress the content of this directory in a zip file in order to import it as plugin
[logs2.txt](https://github.com/makehumancommunity/mpfb2/files/10473280/logs2.txt)
, but it did not work.

**Comment by joepal1976** [comment]
Great, thanks. I think I see the problem in the logs now. I'll see if I can write a fix for it.

Yes, the trick is that it isn't the root from git you need, but the src/mpfb folder. If you have a zip program installed, such as 7zip, you could download the git repo as a zip, extract it and then make a new zip including only the src/mpfb folder. This should be functionally equivalent of a nightly  build. 

Another method is figuring out where your blender addons are installed, find the mpfb directory in there, and simply copy the files from the src/mpfb directory there overwriting the existing files.

**Comment by joepal1976** [comment]
Well, I hope I have fixed the issue now. The problem boils down to me developing on linux and the problem only arising on windows. 

If it still doesn't work, please attach logs again. 

(I really should set up a functional windows development environment too...)

**Comment by ashledombos** [comment]
It works now, congratulations Joel :)

![image](https://user-images.githubusercontent.com/513335/214176166-7b6c82d2-6f00-434a-8f02-6304aa8ea24e.png)

**Comment by ashledombos** [comment]
I was a little too quick, here is what happens when I click on «load» material:

![image](https://user-images.githubusercontent.com/513335/214176544-8b27e084-399f-4089-a470-d4bb47e5b599.png)

**Comment by ashledombos** [comment]
Not sure if I should reopen the issue or if it's unrelated…

**Comment by joepal1976** [comment]
It's so-so related, but it makes sense to keep it in the same issue. 

This is a case of different character encodings being mixed. It is obviously something that should be handled by MPFB in a structured manner, but it is historically something which often tends to cause issues in python when paths are being treated as strings.

It boils down to MPFB not correctly handling the "è" in the "Bibliothèque" part of the path where the asset is stored. 

I'll see what I can do about it.

**Comment by joepal1976** [comment]
I've now played around with a windows user account "åäö ñüé" until I managed to get around the problem. With this is should be possible to load alternative materials, even if there's a non-unicode character somewhere in the parent path.

**Comment by ashledombos** [comment]
Indeed it’s working.
