### ISSUE TITLE
Maybe add a toggle to temporarily suppress shape key removal.

### ISSUE THREAD

**Issue by angavrilov** [makehumancommunity/mpfb2#81]
When you change sliders to change target influence, MPFB automatically adds and removes shape keys it needs to implement the targets. Shape key removal when the influence becomes zero ensures that only the necessary shape keys are present in the mesh, saving memory. However, adding or removing a shape key is significantly more costly than changing influence values, so every time that happens it causes a hiccup.

I wonder if it may be worth it to have a toggle to suppress automatic removal of shape keys while tuning slider values, and instead have a button to remove all unused shapes once the desired final shape is reached.

**Comment by joepal1976** [comment]
This is a good idea for other reasons too. It's a frequent request to be able to export a character with a huge set of available shape keys so that they can be used in the target system. This will more or less require that zero weight targets are allowed.

**Comment by joepal1976** [comment]
Well, the first part is fixed (the toggle). A button for removing targets has yet to be added. I'll keep the issue open.

**Comment by angavrilov** [comment]
It seems to work ok. This toggle plus my new Developer panel buttons for exporting targets are the basis of my new workflow for fixing the breast targets: this option allows testing different slider combinations without losing edited target shape keys, and the button allows re-exporting the edits in basically three clicks.
