### ISSUE TITLE
Caucasian is encoded as "cauc$as" in shape key names.

### ISSUE THREAD

**Issue by angavrilov** [makehumancommunity/mpfb2#84]
It happens because replacing "asian" with "$as" is tried first.

This is clearly a minor issue, and fixing it may cause backward compatibility problems, but it's an obvious glitch.

**Comment by joepal1976** [comment]
I think this one should not cause much trouble to change. The macro details stack should be rebuilt if changing a phenotype slider. But I'll take a closer look before doing anything to see if there's a potential failure scenario.

**Comment by angavrilov** [comment]
One failure scenario I could imagine is it creating a copy of the shape key with a new name, while leaving the old one also active.

**Comment by joepal1976** [comment]
From what I can see, the failure scenario is unlikely to happen, and will be corrected as soon as a phenotype value is modified.

The reapply_macro_details method in TargetService will do the following:

- set all shape keys with a name starting with $md to 0.0
- check if new shape keys needs to be loaded. Here a duplicate might temporarily arise.
- set still relevant shape keys to their appropriate values
- remove any shape key with a name starting with $md and a value which is still 0.0. Here the duplicate will be removed.



will

**Comment by angavrilov** [comment]
I think it works.
