### ISSUE TITLE
The rigify meta rig needs to be weight painted

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#9]
While some parts of the rig has been interpolated from the other rigs, large parts are still from automated weights. These are sub-par to say the least. 

The weight painting needs to be done thoroughly. A start is to fix the most visible errors, such as the jaw not moving the teeth and the breasts having weights on the back of the character.

**Comment by gabrielmontagne** [comment]
Hi, I think the jaw not moving the teeth might not be a weight painting problem.    I'm looking at this video by Todor Nikolov about using the rigify face and he parents the teeth (separated into top/bottom objects) to the teeth bones directly.  https://youtu.be/n8aCBKjPJRE?t=784   I'm not sure that's the only way to do it but it does make sense -- you can then use the teeth bones on the generated mesh also to tweaks certain poses.  The, of course, automatically move with the jaw and face.

**Comment by gabrielmontagne** [comment]
... similar things might apply to the eyes.  

I sense that some of the problems might be from bone placement and scale more than the automatic weights?   For example, the generated neck seems too big?  

Here, on the left, the neck of a default rigify armature, to the right the MH one.
![image](https://user-images.githubusercontent.com/95913/121821716-fc9b5400-cc9a-11eb-89c3-a3ba54e60095.png)

**Comment by joepal1976** [comment]
I've found a bunch of other things which are very strange. 

In the meta-rig, there is a bone named "teeth.B" for the bottom row of teeth. 

When generating, this bone does not get the same treatment as pretty much all other bones. Almost all other bones are automatically renamed to "DEF-...", but not the teeth. This is something controlled by bpy.ops.pose.rigify_generate(), and not a routine added in MH.

However, even if naming the corresponding vertex group "teeth.B", the bone still doesn't modify the vertices in the group. This defies my understanding of how armatures and vertex groups work together. There must be something important that I'm missing.

**Comment by joepal1976** [comment]
As the teeth does indeed not have anything to do with weight painting, I'll deal with that in #10.

Possibly the scale stuff should be a separate issue too.

But the issue with weight painting remains.

**Comment by TACarp** [comment]
I did some essential weight painting but it could still use some fine tuning. I don't understand github pulls very well, so here is a Google Drive link the json file I created. [https://drive.google.com/file/d/1cB9R5nXQLBmo8D2ZAfUzQXMBgF-S7WLL/view?usp=sharing](url) Feel free to use it. I corrected the breasts so they are no longer moving the back. I also corrected the upper eyebrows/ forehead so the whole head isn't distorted. The forehead gets some large wavy ridges if the eyebrows are pushed too far. I am not particularly good at weight painting but the results I have included are serviceable.

**Comment by joepal1976** [comment]
Thanks a lot. This will come in very handy, as my own attempts at weight painting have been pitiful at best. 

I'll take a look at merging this tomorrow.

**Comment by joepal1976** [comment]
Looking at the JSON file, I realize something is funky with it. This stems from the save weights routine which has not properly named the bones in the output. This should be possible to solve, but I had to revert the merge for now.

**Comment by joepal1976** [comment]
This was fixed in PR https://github.com/makehumancommunity/mpfb2/pull/41
