### ISSUE TITLE
About creating a baby

### ISSUE THREAD

**Issue by opdev1004** [makehumancommunity/mpfb2#92]
**Describe the bug**
There's an error for creating a baby.

**Screenshots / logs**
![nobaby](https://user-images.githubusercontent.com/26009893/223792214-dc5eb00a-3565-4eb4-90c9-bdf6f9d94efb.png)

[INFO ] mpfb.init ..............................: Build info 20220904
[INFO ] services.locationservice ...............: mh_user_dir is not explicitly set but autodiscovery is disabled
[INFO ] services.uiservice .....................: Rebuilding the list of available importer presets (for presets panel)
[INFO ] services.uiservice .....................: Rebuilding the list of available importer presets (for importer panel)
[INFO ] mpfb.init ..............................: MPFB initialization has finished.
[INFO ] services.uiservice .....................: Rebuilding the list of available enhanced material settings (for importer panel)
[INFO ] services.uiservice .....................: Rebuilding the list of available eye material settings (for importer panel)

**Platform and versions**
 - OS: Windows
 - Version of Blender: 3.4.1 Steam
 - Version of MPFB (approximate date when you downloaded it is enough): v2.0-a2

**Comment by joepal1976** [comment]
This is a very old build of MPFB, and the issue has been fixed since. Please download the latest build from https://download.tuxfamily.org/makehuman/plugins/ and test again.

**Comment by opdev1004** [comment]
Thank you! I have resolved this by installing latest version as you said.
