### ISSUE TITLE
The MakeTarget version bundled with MPFB generates incomplete targets

### ISSUE THREAD

**Issue by spamrakuen** [makehumancommunity/mpfb2#93]
Hi,

I tried to make a .target using this tool (last buid of MPFB) for first time and I've found that some vertices that I had modified were not output inside the .target file.

I verified many times that the blend shape has the desired number of vertices modified, but for some reason only about half of them are output in the .target file and the other are missing. Maybe I'm doint something wrong... 

I've started both MH and blender, aplied a .target to the default model in MH, then in Blender I've used New Human > From MakeHuman, then I'v used Create Assets > MakeTarget > give a name, new target button, then edit mode, and modified a few vertices. Finally, object mode and, "save target".

I tried to write a small script to workaround this issue and seems to work (not well tested)

```
import bpy

ob = bpy.context.view_layer.objects.active
sk_base = ob.data.shape_keys.key_blocks['Basis']
sk_modif = ob.data.shape_keys.key_blocks['PrimaryTarget']
for vidx, vtx in enumerate(ob.data.vertices):
    base_pos = sk_base.data[vidx].co
    modified_pos = sk_modif.data[vidx].co
    diff = modified_pos - base_pos
    distance = diff.length
    if distance > 0.0001:
        print(vidx, " ", "%.4f" % (diff.x * 10.0), " ", "%.4f" % (diff.z * 10.0), " ", "%.4f" % (diff.y * 10.0))
```

I've created a .target with the output of the console and seems to be working fine inside MH.

**Comment by joepal1976** [comment]
The MakeTarget code should do precisely what your code is doing, so apparently there's a bug in there somewhere.

**Comment by joepal1976** [comment]
I can't replicate this with the simple tests I've made. I'm probably doing something different.

Can you post a blend file with the problem as it looks right before you click the save target button?

**Comment by spamrakuen** [comment]
Here you have

https://filetransfer.io/data-package/mb5tWnph#link

I've modified 8 vertices in the neck, but the "Print Target" only outputs 4 of them.
Maybe it just fails with small changes...

**Comment by joepal1976** [comment]
That makes a lot of sense. That bug will totally exclude all movement along the z axis from consideration when determining if a vertex has moved. 

I've pushed a fix for this. Can you test if it solves your problem?

**Comment by spamrakuen** [comment]
Hi,

Yes, its working now.

Thanks
