### ISSUE TITLE
Finalize new skin shader

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#94]
This is a placeholder for discussing the new skin shader.

A standalone demo file can be downloaded from http://www.makehumancommunity.org/content/skin_v2_demo_20230309.html. 

If you rather test on your own character and/or with a different skin texture, you can also create a new instance of the material in recent (since early march) builds of MPFB2. Just create your character and equip a skin as usual. Then go to operations -> material -> experimental and click "create v2 skin". The new material will then use the already equipped diffuse texture.

**Comment by fraang** [comment]
May I ask for finished render? I have no access to Blender right now.

**Comment by joepal1976** [comment]
This can be arranged, but the images are unsuitable for pasting on github. If you give me an email address either here or by sending a messenger message to the makehuman facebook page, I'll send a few renders.

**Comment by joepal1976** [comment]
I have now added initial support for the v2 skin shader on selecting a skin in the library and on loading from preset. There is still no support for serializing skin settings.

**Comment by joepal1976** [comment]
The new skin shader is merged and working as expected.
