### ISSUE TITLE
Mesh geometry incorrect when using 'Import Human'

### ISSUE THREAD

**Issue by JerbusF** [makehumancommunity/mpfb2#99]
Using Blender 3.5.0 and MPFB2 v2.0.0-a2, an imported mesh from MH 1.2.0 shows issues with mesh geometry which aren't present with the equivalent MHPB1 process.

MFPB2:
![image](https://user-images.githubusercontent.com/132120404/235283461-2ba552f9-7e49-47d7-83d0-5ea8d0267368.png)

MFPB1:
![image](https://user-images.githubusercontent.com/132120404/235283530-d9924efb-c032-409f-9431-fbb01f05527e.png)

The result is the same whether or not 'smooth' has been applied to the model in MakeHuman, and is not affected by any settings in the subdivision modifier (levels viewport or render).

I am not sure if this is a bug or not, and this is also my first contribution to github, so my apologies if this is an incorrect approach.

**Comment by joepal1976** [comment]
That's ok, but I'm not sure I understand what the specific problem is. Is it that the mesh does not seem entirely smooth in the MPFB2 case?

Can you attach an MHM file, so I can do some testing locally? This assuming that the character only uses public assets.

Another thing you can test is to open the MHM file directly in MPFB2 (new human -> from presets -> load MHM) rather than use the online import from MakeHuman. Is the end result the same?

**Comment by JerbusF** [comment]
I am unable to attach MHM files, as a workaround I have just changed the extension to txt:
[charly_mh.txt](https://github.com/makehumancommunity/mpfb2/files/11360151/charly_mh.txt)

It uses community targets and clothes, nothing custom.

![image](https://user-images.githubusercontent.com/132120404/235325957-ca3cb883-3350-42dc-adbd-0b3443d5f57f.png)

When opening the mhm file directly from presets the subdivision modifier works in viewport render as intended. So at least in this specific case, the issue with the subdivision modifier not affecting the mesh in either viewport or render seems specific to the online import.

**Comment by joepal1976** [comment]
Having looked into this, I'm still wondering if I'm looking at the same thing. This is the sharp point I'm assuming you're talking about:

![jagged1](https://user-images.githubusercontent.com/10105480/236157808-0f00361e-bdd7-4bfe-a11c-c54bba7309e2.png)

However, if I change "levels viewport" to match the same setting as in your MPFB1 screenshot, the point smooths out as expected:

![jagged2](https://user-images.githubusercontent.com/10105480/236158001-fda0e537-84f8-4444-9d77-fc6cdf75026c.png)

Am I looking at the wrong thing?

**Comment by joepal1976** [comment]
No more info for two months, closing
